#------------------------------------------------------------------------------------------------------
# This log4j will create separate file for logs and SystemOut.log file will not write anything.
# Antony, 2018-Nov-12
# Ashwin C	2020-FEB-14
#------------------------------------------------------------------------------------------------------
#------Last deployment in production---14/06/20,24/08/20
#------------------------------------------------------
# Root logger option
#It will Write only Info log in Log File
log4j.rootLogger=INFO, file
 
# Direct log messages to a log file
log4j.appender.file=org.apache.log4j.RollingFileAppender
#UAT
log4j.appender.file.File=/ftrade/FTI_Repositories/Localisation_logs/ODC_Bulkupload/ODC_Bulkupload.log
 
log4j.appender.file.MaxFileSize=10MB
log4j.appender.file.MaxBackupIndex=40
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
# Below It will display in Console
# Direct log messages to stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
 
#To Run locally
#comment web.xml
#comment DBconnectionutility.java JNDI
#uncomment MakerHomeDAO.java line :4672
 
#Last changes
##MakerHomeDAO.java ---Line:2822
##MakerHomeDAO.java ----Line:4598--commented
##MakerHomeDAO.java ----Line:4489--commented
 
 
##MakerHomeDAO.java ------Line:2594---Changed by Ashwin 2020-02-14 --- INC000003713067: unable to upload ODC
 
##MakerHomeDAO.java ------Line:6049---Changed by Ashwin 2020-05-13 --- INC000003967360: Incorrect calculation of Utilization amount
##MakerHomeDAO.java ------Line:3947,3956---Changed by Ashwin 2020-05-20 --- REQ000004265263: Duplicate transaction getting created
 
##MakerHomeDAO.java ------Line:4276,4280,4310,4352--Changed by Ashwin 2020-07-20 --- INC000004191577:Amount to be collected field not populating correctly
##bulkUpload.js ----------Line:84 --Changed by Ashwin 2020-07-20 --- INC000004173057 :Duplicate transaction getting created ,as user request ,implemented unique constrain in the table
##MakerHomeDAO.java ------Line:3654--Changed by Ashwin 2020-07-20 --- INC000004191577:Failure records not showing while upload.so there was amount mismatch after uploading
##-------------------Appsec Approved code---------Changed by Ashwin 2020-08-12
 
 
###---------------------Table changes-----------------------------
###--- Modified by Ashwin 2020-07-21-- 
###---alter table ETTDM_BULKUPLOAD_STAGING add  HOSTNAME varchar(15);
###---create table ett_odc_bulkupload_apiserver ( Batch varchar2(10),THEIRREF varchar2(30) ,REQUEST clob,RESPONSE clob ,status varchar2(10),Upload_Time TIMESTAMP (6),Request_Time TIMESTAMP (6) ,Response_Time TIMESTAMP (6),Node varchar2(20));
###---create unique index BULKINDEX on ett_odc_bulkupload_apiserver(Batch,THEIRREF);
###---update ETTDM_BULKUPLOAD_STAGING set UPDATED     ='Y' where TI_STATUS = 'SUCCEEDED' AND UPDATED     ='N' ;