poackage in.co.localization.utility;
 
public abstract interface ActionConstantsQuery

  extends ActionConstants, ErrorCodesInterface

{

  public static final String userName = "root";

  public static final String password = "root";

  public static final String dbName = "demohab_myshare";

  public static final String url = "jdbc:mysql://localhost:3306/demohab_myshare";

  public static final String driver = "com.mysql.jdbc.Driver";

  public static final String SHIPPINGBILLAMOUNT = "SHIPPINGBILLAMOUNT";

  public static final String SHIPPINGBILLDATE = "SHIPPINGBILLDATE";

  public static final String SHIPPINGBILLNO = "SHIPPINGBILLNO";

  public static final String INVOICESERIALNO = "INVOICESERIALNO";

  public static final String INVOICENO = "INVOICENO";

  public static final String COL_NEWADCODE = "NEWADCODE";

  public static final String COL_EXISTINGADCODE = "EXISTINGADCODE";

  public static final String TRANSMISSIONDATE = "TRANSMISSIONDATE";

  public static final String TRANSFERSTATUS = "TRANSFERSTATUS";

  public static final String FILE_NO = "FILE_NO";

  public static final String CREATEDON = "CREATEDON";

  public static final String LASTUPDATE = "LASTUPDATE";

  public static final String USERID = "USERID";

  public static final String COL_SHIPID = "SHIP_ID";

  public static final String BILLREFNO = "BILLREFNO";

  public static final String COL_GR_PART_PAY_REF = "GR_PART_PAY_REF";

  public static final String COL_GR_IE_CODE = "GR_IE_CODE";

  public static final String COL_GR_AD_CODE = "GR_AD_CODE";

  public static final String COL_GR_CIF_ID = "GR_CIF_ID";

  public static final String COL_GR_CIF_NAME = "GR_CIF_NAME";

  public static final String COL_GR_TXN_CCY = "GR_TXN_CCY";

  public static final String COL_GR_FC_AMT = "GR_FC_AMT";

  public static final String COL_ADDRESS1 = "ADDRESS1";

  public static final String COL_COUNTRY = "COUNTRY";

  public static final String COL_TISHPBILLNO = "tishbillno";

  public static final String COL_BILLDATE = "billdate";

  public static final String COL_TIPORTCODE = "tiportcode";

  public static final String COL_TIFORM = "tiformno";

  public static final String COL_TIBILLAMT = "TIBILLAMT";

  public static final String COL_TIBUYERNAME = "TIBUYER_NAME";

  public static final String COL_TIBUYERFULLNAME = "TIBUYER_FULLNAME";

  public static final String COL_TIBUYERCOUNTRY = "TIBUYER_COUNTRY";

  public static final String COL_TIBUYERNAME1 = "TIBUYER_FULLNAME";

  public static final String COL_TIBUYERCOUNTRY1 = "TIBUYER_COUNTRYNAME";

  public static final String COL_SHPBILLAMT = "SHPBILLAMT";

  public static final String COL_SHPBILLCURR = "SHPBILLCURR";

  public static final String COL_SHIPBILLNO = "SHIPBILLNO";

  public static final String COL_SHIPBILLDATE = "SHIPBILLDATE";

  public static final String COL_PORTCODE = "PORTCODE";

  public static final String COL_LEODATE = "LEODATE";

  public static final String COL_CUSTNO = "CUSTNO";

  public static final String COL_FORMNO = "FORMNO";

  public static final String COL_IECODE = "IECODE";

  public static final String COL_ADCODE = "ADCODE";

  public static final String COL_EXPORTAGENCY = "EXPORTAGENCY";

  public static final String COL_EXPORTTYPE = "EXPORTTYPE";

  public static final String COL_RECIND = "RECIND";

  public static final String COL_COUNTRYDEST = "COUNTRYDEST";

  public static final String COL_RECORDINDICATOR = "RECORDINDICATOR";

  public static final String COL_TIDIRECTDISPATCH = "TIDIRECTDISPATCH";

  public static final String COL_TIDATEOFNGO = "TIDATEOFNGO";

  public static final String SHIPPINGBILLCURR = "SHIPPINGBILLCURR";

  public static final String COL_INVSERIALNO = "INVSERIALNO";

  public static final String COL_INVNO = "INVNO";

  public static final String COL_INVDATE = "INVDATE";

  public static final String COL_FOBCURRCODE = "FOBCURRCODE";

  public static final String COL_FOBAMT = "FOBAMT";

  public static final String COL_FRIEGHTCURRCODE = "FRIEGHTCURRCODE";

  public static final String COL_FRIEGHTAMT = "FRIEGHTAMT";

  public static final String COL_INSCURRCODE = "INSCURRCODE";

  public static final String COL_INSAMT = "INSAMT";

  public static final String COL_COMMCURRCODE = "COMMCURRCODE";

  public static final String COL_COMMAMT = "COMMAMT";

  public static final String COL_DISCURRCODE = "DISCURRCODE";

  public static final String COL_DISAMT = "DISAMT";

  public static final String COL_DEDAMT = "DEDAMT";

  public static final String COL_DEDCURRCODE = "DEDCURRCODE";

  public static final String COL_PKGCURRCODE = "PKGCURRCODE";

  public static final String COL_PKGAMT = "PKGAMT";

  public static final String COL_INVFRAMT = "INVFRAMT";

  public static final String COL_INSUAMT = "INSUAMT";

  public static final String COL_EVENTREFNO = "EVENTREFNO";

  public static final String COL_CUSTSERIALNO = "CUSTSERIALNO";

  public static final String COL_CUSTNAME = "CUSTNAME";

  public static final String COL_BILLCURR = "BILLCURR";

  public static final String COL_BILLAMT = "BILLAMT";

  public static final String COL_CIFNO = "CUSTCIFNO";

  public static final String COL_TRANSREF = "TRANSREF";

  public static final String COL_TRANSEVENTREFNO = "TRANSEVENTREFNO";

  public static final String COL_TRANSDATE = "TRANSDATE";

  public static final String COL_VALUE_DATE = "VALUE_DATE";

  public static final String COL_TRANSCURR = "TRANSCURR";

  public static final String COL_TRANSAMT = "TRANSAMT";

  public static final String COL_RSTATUS = "RSTATUS";

  public static final String COL_PAY_SERIAL_NO = "PAY_SERIAL_NO";

  public static final String COL_EXCHANGERATE = "EXCHANGERATE";

  public static final String COL_CURREXRATE = "CURREXRATE";

  public static final String COL_WRITEOFFAMOUNT = "WRITEOFFAMOUNT";

  public static final String COL_WRITEOFFDATE = "WRITEOFFDATE";

  public static final String COL_BANKCHRGS = "BANKCHRGS";

  public static final String COL_BOENO = "BOENO";

  public static final String COL_BOEDATE = "BOEDATE";

  public static final String COL_PORTDISCHARGE = "PORTDISCHARGE";

  public static final String COLUMN_FILE_NAME = "FILE_NAME";

  public static final String FILENAME = "FILENAME";

  public static final String CHECKSUM = "checkSum";

  public static final String NOOFSHIPPING = "noOfShippingBills";

  public static final String NEXTVAL = "nextval";

  public static final String SHIPPINGBILLS = "shippingBills";

  public static final String SHIPPINGBILL = "shippingBill";

  public static final String PORTCODE = "portCode";

  public static final String EXPORTTYPE = "exportType";

  public static final String REDIND = "recordIndicator";

  public static final String SHIPBILLNO = "shippingBillNo";

  public static final String SHIPBILLDATE = "shippingBillDate";

  public static final String FORMNO = "formNo";

  public static final String LEODATE = "LEODate";

  public static final String IECODE = "IECode";

  public static final String CHGIECODE = "changedIECode";

  public static final String ADCODE = "adCode";

  public static final String PORTDISCHARGE = "portOfDischarge";

  public static final String BOEDATE = "billOfEntryDate";

  public static final String BOENO = "billOfEntryNumber";

  public static final String WRTSEQ = "writeoffSequence";

  public static final String PAYSEQ = "paymentSequence";

  public static final String IRMNO = "IRMNumber";

  public static final String FIRCNumber = "FIRCNumber";

  public static final String REMADCODE = "remittanceAdCode";

  public static final String THIRDPARTY = "thirdParty";

  public static final String RELCURR = "realizedCurrencyCode";

  public static final String RELDATE = "realizationDate";

  public static final String ADEXPORT = "adExportAgency";

  public static final String DIRIND = "directDispatchIndicator";

  public static final String ADBILLNO = "adBillNo";

  public static final String DATEOFNGO = "dateOfNegotiation";

  public static final String BUYERNAME = "buyerName";

  public static final String BUYERCOUNTRY = "buyerCountry";

  public static final String ERRORCODES = "errorCodes";

  public static final String REALEXT = "realizationExtensionInd";

  public static final String LETTERNO = "letterNo";

  public static final String LETTERDATE = "letterDate";

  public static final String EXTREALDATE = "extendedRealizationDate";

  public static final String NOOFINVOICE = "noOfInvoices";

  public static final String INVOICES = "invoices";

  public static final String INVOICE = "invoice";

  public static final String INVSERNO = "invoiceSerialNo";

  public static final String INVNO = "invoiceNo";

  public static final String INVDATE = "invoiceDate";

  public static final String REALSTATUS = "realizationStatus";

  public static final String FIRCNO = "FIRCNumber";

  public static final String FIRCADCODE = "FIRCADCode";

  public static final String REALCURRCODE = "realizedCurrencyCode";

  public static final String REALDATE = "realizationDate";

  public static final String ACCNO = "accountNumber";

  public static final String BANKCHGAMT = "bankingChargesAmt";

  public static final String FOBAMT = "FOBAmt";

  public static final String FOBAMTIC = "FOBAmtIC";

  public static final String FREIGHTAMT = "freightAmt";

  public static final String FREIGHTAMTIC = "freightAmtIC";

  public static final String INSAMT = "insuranceAmt";

  public static final String INSAMTIC = "insuranceAmtIC";

  public static final String COMMAMT = "commissionAmt";

  public static final String COMMAMTIC = "commissionAmtIC";

  public static final String PKGAMT = "packagingChargesAmt";

  public static final String PKGAMTIC = "packagingChargesAmtIC";

  public static final String DEDAMT = "deductionAmt";

  public static final String DEDTAMT = "deductionsAmt";

  public static final String DEDAMTIC = "deductionAmtIC";

  public static final String DISAMT = "discountAmt";

  public static final String DISAMTIC = "discountAmtIC";

  public static final String CLOSEIND = "closeOfBillIndicator";

  public static final String REMITTERNAME = "remitterName";

  public static final String REMITTERCOUNTRY = "remitterCountry";

  public static final String INVERRORCODES = "invoiceErrorCodes";

  public static final String CUSTNO = "custNo";

  public static final String EXPORTAGENCY = "exportAgency";

  public static final String COUNTDEST = "countryOfDestination";

  public static final String FOBCURR = "FOBCurrencyCode";

  public static final String FREIGHTCURR = "freightCurrencyCode";

  public static final String INSCURR = "insuranceCurrencyCode";

  public static final String COMMCURR = "commissionCurrencyCode";

  public static final String DEDCURR = "deductionsCurrencyCode";

  public static final String DISCURR = "discountCurrencyCode";

  public static final String PKGCURR = "packagingCurrencyCode";

  public static final String TRANSDATE = "transmissionDate";

  public static final String EXTADCODE = "existingAdCode";

  public static final String NEWADCODE = "newAdCode";

  public static final String ERRORCODE = "errorCode";

  public static final String SHIPIND = "shipmentIndicator";

  public static final String WRITEOFFIND = "writeoffIndicator";

  public static final String WRITEOFFAMT = "writeoffAmount";

  public static final String WRITEOFFDATE = "writeoffDate";

  public static final String REALIZATIONAMOUNT = "REALIZATIONAMOUNT";

  public static final String REALIZATIONCURR = "REALIZATIONCURR";

  public static final String COLUMN_SKEY80 = "SKEY80";

  public static final String TABLE_ETT_EDPMS_SHP_TBL = "ETT_EDPMS_SHP";

  public static final String TABLE_ETT_EDPMS_SHP_INV_TBL = "ETT_EDPMS_SHP_INV";

  public static final String TABLE_ETT_GR_SHP_TBL = "ETT_GR_SHP_TBL";

  public static final String TABLE_ETT_GR_INV_TBL = "ETT_GR_INV_TBL";

  public static final String TABLE_ETTV_GR_TISHP_DETAILS = "ETTV_GR_TISHP_DETAILS";

  public static final String ETT_PRN_REC_DELETE = "ETT_PRN_REC_DELETE";

  public static final String TI_TXN_REF = "TI_TXN_REF";

  public static final String TIPART_PAYREF = "TIPART_PAYREF";

  public static final String TABLE_ETT_REL_GR_SHP_TBL = "ETT_GR_REL_SHP_TBL";

  public static final String TABLE_ETT_REL_GR_INV_TBL = "ETT_GR_REL_INV_TBL";

  public static final String TABLE_ETT_TRR_SHP_STG = "ETT_TRR_SHP_STG";

  public static final String IS_DATA_AVAILABLE = "SELECT COUNT(1) FROM  TABLE  WHERE COLUMN=?";

  public static final String ONE_COLUMN_AVAILABLE = "SELECT COUNT(1) FROM  TABLE  WHERE COLUMN1=?";

  public static final String TWO_COLUMN_AVAILABLE = "SELECT COUNT(1) as COUNT FROM  TABLE_NAME  WHERE COLUMN_NAME1=? AND COLUMN_NAME2=? ";

  public static final String THREE_COLUMN_AVAILABLE1 = "SELECT COUNT(1) as COUNT FROM  TABLE_NAME  WHERE COLUMN_NAME1=? AND COLUMN_NAME2=? AND COLUMN_NAME3=?";

  public static final String THREE_COLUMN_AVAILABLE = "SELECT COUNT(1) FROM  TABLE_NAME  WHERE COLUMN_NAME1=? AND COLUMN_NAME2=? AND COLUMN_NAME3=?";

  public static final String FOUR_COLUMN_AVAILABLE = "SELECT COUNT(1) FROM  TABLE_NAME  WHERE COLUMN_NAME1=? AND COLUMN_NAME2=? AND COLUMN_NAME3=? AND COLUMN_NAME4=?";

  public static final String SEVEN_COLUMN_AVAILABLE = "SELECT COUNT(1) FROM  TABLE_NAME  WHERE COLUMN_NAME1=? AND COLUMN_NAME2=? AND COLUMN_NAME3=? AND COLUMN_NAME4=? AND COLUMN_NAME5=? AND COLUMN_NAME6=? AND COLUMN_NAME7=?";

  public static final String FIVE_COLUMN_AVAILABLE = "SELECT COUNT(1) FROM  TABLE_NAME  WHERE COLUMN_NAME1=? AND COLUMN_NAME2=? AND COLUMN_NAME3=? AND COLUMN_NAME4=? AND COLUMN_NAME5=?";

  public static final String SHP_REL_COLUMN_AVAILABLE = "SELECT COUNT(1) FROM  TABLE_NAME  WHERE COLUMN_NAME1=? AND COLUMN_NAME2=? AND COLUMN_NAME3=?  AND COLUMN_NAME4=? AND COLUMN_NAME5=? AND COLUMN_NAME6=?";

  public static final String INV_REL_COLUMN_AVAILABLE = "SELECT COUNT(1) FROM  TABLE_NAME  WHERE COLUMN_NAME1=? AND COLUMN_NAME2=? AND COLUMN_NAME3=? \tAND COLUMN_NAME4=? AND COLUMN_NAME5=? AND COLUMN_NAME6=? AND COLUMN_NAME7=? AND COLUMN_NAME8=? ";

  public static final String FETCH_ADTRANSFER_VALUE = "SELECT SHIP_ID,IECODE,TO_CHAR(TO_DATE(SHIPPINGBILLDATE, 'ddmmyyyy'),'dd-mm-yyyy') as SHIPPINGBILLDATE,PORTCODE,FORMNO,EXPORTAGENCY,EXPORTTYPE,SHIPPINGBILLNO,EXISTINGADCODE,NEWADCODE FROM ETT_TRR_SHP_STG WHERE TRANSFERSTATUS='Pending' OR TRANSFERSTATUS IS NULL";

  public static final String GET_ADTRANSFER_VALUE = "SELECT IECODE,SHIPPINGBILLDATE,PORTCODE,FORMNO,EXPORTAGENCY,EXPORTTYPE,SHIPPINGBILLNO,EXISTINGADCODE,NEWADCODE FROM ETT_TRR_SHP_STG WHERE TRANSFERSTATUS='PENDING' OR TRANSFERSTATUS IS NULL AND SHIPPINGBILLNO =? AND PORTCODE =?";

  public static final String UPDATE_ADTRANSFER_VALUE = "UPDATE ETT_TRR_SHP_STG SET SHIPPINGBILLNO =?, SHIPPINGBILLDATE =?, PORTCODE =?, EXPORTAGENCY =?, EXPORTTYPE =?, FORMNO =?, IECODE =?, EXISTINGADCODE =?, NEWADCODE =?, FILE_NO =?, TRANSFERSTATUS =?,LASTUPDATE =to_timestamp(?, 'DD-MM-YYYY HH12:MI:SS'),USERID =?  WHERE SHIP_ID =?";

  public static final String INSERT_ADTRANSFER_VALUE = "Insert into ETT_TRR_SHP_STG (SHIP_ID,SHIPPINGBILLNO,SHIPPINGBILLDATE,PORTCODE,EXPORTAGENCY,EXPORTTYPE,FORMNO,IECODE,EXISTINGADCODE,NEWADCODE,FILE_NO,TRANSFERSTATUS,CREATEDON,USERID) VALUES (TRR_SHP_SEQNO.NEXTVAL,?,?,?,?,?,?,?,?,?,?,?,to_timestamp(?, 'DD-MM-YYYY HH12:MI:SS'),?)";

  public static final String UPDATE_GR_SHP_TBL = "UPDATE ETT_GR_SHP_TBL SET BILLCURR=?, BILLAMT=?, LEODATE=TO_DATE(?, 'DD-MM-YYYY'), CUSTSERIALNO=?, FORMNO=?, IECODE=?, ADCODE=?, EXPORTAGENCY=?,EXPORTTYPE=?, RECORDIND=?, COUNTRYOFDEST=?, DATEOFNEG=TO_DATE(?, 'DD-MM-YYYY'), ADBILLNO=?, DIRECTDISPIND=?, BUYERNAME=?, BUYERCOUNTRY=?, RODSTATUS=?,LASTUPDATE=to_timestamp(?, 'DD-MM-YYYY HH12:MI:SS'), REMARKS=?, SHIPPINGBILLCURR=?,SHIPPINGBILLAMOUNT=?,USERID=? WHERE  BILLREFNO=? AND EVENTREFNO=? AND SHIPBILLNO=? AND SHIPBILLDATE=? AND PORTCODE=?";

  public static final String INSERT_GR_SHP_TBL = "INSERT INTO ETT_GR_SHP_TBL (GRNUMBER, BILLREFNO,EVENTREFNO, CUSTCIFNO, CUSTNAME, BILLCURR, BILLAMT, IECODE, ADCODE, SHIPBILLNO, SHIPBILLDATE, PORTCODE, LEODATE, CUSTSERIALNO, FORMNO, CHANGEDIECODE, EXPORTAGENCY, EXPORTTYPE, RECORDIND, COUNTRYOFDEST, DATEOFNEG, ADBILLNO, DIRECTDISPIND, BUYERNAME, BUYERCOUNTRY, RODSTATUS,GRTYPE,REMARKS,CREATEDON,USERID,SHIPPINGBILLCURR,SHIPPINGBILLAMOUNT) VALUES (SEQ_NO_ETT_GR_SHP_TBL.NEXTVAL,?,?,?,?,?,?,?,?,?,?,?,TO_DATE(?, 'DD-MM-YYYY'),?,?,?,?,?,?,?,TO_DATE(?, 'DD-MM-YYYY'),?,?,?,?,?,?,?,to_timestamp(?, 'DD-MM-YYYY HH12:MI:SS'),?,?,?)";

  public static final String UPDATE_GR_INV_TBL = "UPDATE ETT_GR_INV_TBL SET INVDATE=TO_DATE(?, 'DD-MM-YYYY'),  INVTOT=?, FOBCURRCODE=?, FOBAMT=?, FRIEGHTCURRCODE=?, FRIEGHTAMT=?, INSCURRCODE=?, INSAMT=?, COMMCURRCODE=?, COMMAMT=?, DISCURRCODE=?, DISAMT=?, DEDCURRCODE=?, DEDAMT=?, PKGCURRCODE=?, PKGAMT=?, LASTUPDATE =to_timestamp(?, 'DD-MM-YYYY HH12:MI:SS'), USERID=? WHERE BILLREFNO=? AND EVENTREFNO=? AND INVSERIALNO=? AND INVNO=?";

  public static final String INSERT_GR_INV_TBL = "INSERT INTO ETT_GR_INV_TBL (GRNUMBER, SHIPBILLNO, SHIPBILLDATE, PORTCODE, BILLREFNO, EVENTREFNO,INVSERIALNO, INVNO, INVDATE, INVTOT, FOBCURRCODE, FOBAMT, FRIEGHTCURRCODE, FRIEGHTAMT,INSCURRCODE, INSAMT, COMMCURRCODE, COMMAMT, DISCURRCODE, DISAMT, DEDCURRCODE, DEDAMT, PKGCURRCODE, PKGAMT,CREATEDDATE,USERID) VALUES(SEQ_NO_ETT_GR_INV_TBL.NEXTVAL,?,?,?,?,?,?,?,TO_DATE(?, 'DD-MM-YYYY'),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,to_timestamp(?, 'DD-MM-YYYY HH12:MI:SS'),?)";

  public static final String TABLE_ETT_SHP_ROD_ACK_STG = "ETT_SHP_ROD_ACK_STG";

  public static final String COL_SHIPPINGBILLNO = "SHIPPINGBILLNO";

  public static final String COL_SHIPPINGBILLDATE = "SHIPPINGBILLDATE";
 
public static final String GET_ROD_FILE_NAME = "SELECT FILE_NAME FROM ETT_ROD_ACK_FILES WHERE FILE_NAME=?";

  public static final String INS_ETT_ROD_ACK_FILES_TBL = "INSERT INTO ETT_ROD_ACK_FILES(FILE_NO,NO_OF_SHIPPING_BILLS,FILE_NAME,STATUS,PROCESSED_DATE) values(?,?,?,?,TO_DATE(?,'DD-MM-YYYY'))";

  public static final String GET_ROD_SHIP_VALUE = "SELECT ERRORCODES FROM ETT_SHP_ROD_ACK_STG WHERE SHIPPINGBILLNO=? AND SHIPPINGBILLDATE=? AND PORTCODE=? AND RECORDINDICATOR=? ";

  public static final String INS_ROD_XML_DATA = "INSERT INTO ETT_SHP_ROD_ACK_STG(PORTCODE,EXPORTTYPE,RECORDINDICATOR,SHIPPINGBILLNO,SHIPPINGBILLDATE,FORMNO,LEODATE,IECODE,CHANGEDIECODE,ADCODE,ADEXPORTAGENCY,DIRECTDISPATCHINDICATOR,ADBILLNO,DATEOFNEGOTIATION,BUYERNAME,BUYERCOUNTRY,FILE_NO,ERRORCODES) VALUES(?,?,?,?,?,?,TO_DATE(?, 'DD-MM-YYYY'),?,?,?,?,?,?,TO_DATE(?, 'DD-MM-YYYY'),?,?,?,?)";

  public static final String INS_TEMP_ROD_XML_DATA = "INSERT INTO ETT_TEMP_SHP_ROD_ACK_STG(PORTCODE,EXPORTTYPE,RECORDINDICATOR,SHIPPINGBILLNO,SHIPPINGBILLDATE,FORMNO,LEODATE,IECODE,CHANGEDIECODE,ADCODE,ADEXPORTAGENCY,DIRECTDISPATCHINDICATOR,ADBILLNO,DATEOFNEGOTIATION,BUYERNAME,BUYERCOUNTRY,FILE_NO,ERRORCODES) VALUES(?,?,?,?,?,?,TO_DATE(?, 'DD-MM-YYYY'),?,?,?,?,?,?,TO_DATE(?, 'DD-MM-YYYY'),?,?,?,?)";

  public static final String TABLE_ETT_PEN_SHP_ACK_STG = "ETT_PEN_SHP_ACK_STG";

  public static final String GET_PEN_FILE_NAME = "SELECT FILE_NAME FROM ETT_PEN_ACK_FILES WHERE FILE_NAME=?";

  public static final String INS_ETT_PEN_ACK_FILES = "INSERT INTO ETT_PEN_ACK_FILES(FILE_NO,NO_OF_SHIPPING_BILLS,FILE_NAME,STATUS,PROCESSED_DATE) values(?,?,?,?,TO_DATE(?,'DD-MM-YYYY'))";

  public static final String GET_PEN_SHIP_VALUE = "SELECT ERRORCODES FROM ETT_PEN_SHP_ACK_STG WHERE SHIPPINGBILLNO=? AND SHIPPINGBILLDATE=? AND PORTCODE=? AND RECORDINDICATOR=?";

  public static final String INS_PEN_XML_DATA = "INSERT INTO ETT_PEN_SHP_ACK_STG(PORTCODE,EXPORTTYPE,RECORDINDICATOR,SHIPPINGBILLNO,SHIPPINGBILLDATE,FORMNO,LEODATE,ADCODE,IECODE,REALIZATIONEXTENSIONIND,LETTERNO,LETTERDATE,EXTENDEDREALIZATIONDATE,FILE_NO,ERRORCODES) values(?,?,?,?,?,?,TO_DATE(?, 'DD-MM-YYYY'),?,?,?,?,TO_DATE(?, 'DD-MM-YYYY'),TO_DATE(?, 'DD-MM-YYYY'),?,?)";

  public static final String TABLE_ETT_PRN_SHP_ACK_STG = "ETT_PRN_SHP_ACK_STG";

  public static final String GET_PRN_FILE_NAME = "SELECT FILE_NAME FROM ETT_PRN_ACK_Files WHERE FILE_NAME=?";

  public static final String INS_ETT_PRN_ACK_FILES = "INSERT INTO ETT_PRN_ACK_FILES(FILE_NO,NO_OF_SHIPPING_BILLS,NO_OF_INVOICES,FILE_NAME,STATUS,PROCESSED_DATE) values(?,?,?,?,?,TO_DATE(?,'DD-MM-YYYY'))";

  public static final String INS_PRN_XML_DATA = "INSERT INTO ETT_PRN_SHP_ACK_STG(PORTCODE,EXPORTTYPE,RECORDINDICATOR,SHIPPINGBILLNO,SHIPPINGBILLDATE,FORMNO,LEODATE,ADCODE,PAY_SEQNO,INWARDNO,FIRCNO,REM_ADCODE,PAY_PARTY,REALIZATONCURR,REALIZATONDATE,FILE_NO,ERRORCODES,GR_NUMBER) values(?,?,?,?,?,?,TO_DATE(?, 'DD-MM-YYYY'),?,?,?,?,?,?,?,TO_DATE(?, 'DD-MM-YYYY'),?,?,?)";

  public static final String GET_PRN_INV = "SELECT INVOICESERIALNO,INVOICENO FROM ETT_PRN_SHP_INV_ACK_STG WHERE INVOICESERIALNO=? AND INVOICENO=?";

  public static final String INS_ETT_PRN_SHP_INV_ACK_STG = "INSERT INTO ETT_PRN_SHP_INV_ACK_STG(INVOICESERIALNO,INVOICENO,INVOICEDATE,ACCOUNTNUMBER,BANK_CHG,FOBAMT,FOBAMTIC,FREIGHTAMT,FREIGHTAMTIC,INSURANCEAMT,INSURANCEAMTIC,REMITTERNAME,REMITTERCOUNTRY,CLOSEOFBILLINDICATOR,FILE_NO,SHIPPINGBILLNO,SHIPPINGBILLDATE,PORTCODE,FORMNO,PAY_SEQNO,INVOICEERRORCODES,GR_SHP_NO) values(?,?,TO_DATE(?, 'DD-MM-YYYY'),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

  public static final String GET_MDF_FILE_NAME = "SELECT FILENAME  FROM ETT_EDPMS_FILES WHERE FILENAME =?";

  public static final String INS_ETT_EDPMS_FILES = "INSERT INTO ETT_EDPMS_FILES(FILENO,NOOFSHIPBILLS,NOOFINV,FILENAME,STATUS,PROCESSDATE) values(?,?,?,?,?,TO_DATE(?,'DD-MM-YYYY'))";

  public static final String GET_EDI_SHIP_VALUE = "SELECT NVL(RECIND,'1') AS RECIND FROM ETT_EDPMS_SHP WHERE SHIPBILLNO=? AND SHIPBILLDATE =? AND PORTCODE=?";

  public static final String INS_EDI_SHIP_DATA = "INSERT INTO ETT_EDPMS_SHP(SHIPBILLNO,SHIPBILLDATE,PORTCODE,LEODATE,CUSTNO,FORMNO,IECODE,ADCODE,EXPORTAGENCY,EXPORTTYPE,RECIND,COUNTRYDEST,FILENO)values(?,?,?,TO_DATE(?, 'DD-MM-YYYY'),?,?,?,?,?,?,?,?,?)";

  public static final String INS_TEMP_EDI_SHIP_DATA = "INSERT INTO ETT_TEMP_EDPMS_SHP(SHIPBILLNO,SHIPBILLDATE,LEODATE,CUSTNO,FORMNO,IECODE,ADCODE,PORTCODE,EXPORTAGENCY,EXPORTTYPE,RECIND,COUNTRYDEST,FILENO)SELECT SHIPBILLNO,SHIPBILLDATE,LEODATE,CUSTNO,FORMNO,IECODE,ADCODE,PORTCODE,EXPORTAGENCY,EXPORTTYPE,RECIND,COUNTRYDEST,FILENO FROM ETT_EDPMS_SHP WHERE  SHIPBILLNO=? AND SHIPBILLDATE=? AND PORTCODE=?";

  public static final String UPDATE_EDI_SHIP_DATA = "UPDATE ETT_EDPMS_SHP SET LEODATE=TO_DATE(?, 'DD-MM-YYYY'), CUSTNO=?,FORMNO=?, IECODE=?,ADCODE=?,EXPORTAGENCY=?,EXPORTTYPE=?,RECIND=?,COUNTRYDEST=?,FILENO=? WHERE SHIPBILLNO=? AND SHIPBILLDATE=? AND PORTCODE=?";

  public static final String UPDATE_EDI_SHIP_CAN_DATA = "UPDATE ETT_EDPMS_SHP SET RECIND=?,FILENO=? WHERE  SHIPBILLNO=? AND SHIPBILLDATE=? AND PORTCODE=? ";

  public static final String GET_EDI_INV_VALUE = "SELECT INVSERIALNO,INVNO FROM ETT_EDPMS_SHP_INV WHERE INVSERIALNO=? AND INVNO=?";

  public static final String GET_EDI_INV_VAL = "SELECT COUNT(*) AS COUNT FROM ETT_EDPMS_SHP_INV WHERE  SHIPBILLNO=? AND SHIPBILLDATE =? AND PORTCODE=? AND INVSERIALNO=? AND INVNO=? ";

  public static final String INS_EDI_INV_DATA = "INSERT INTO ETT_EDPMS_SHP_INV(SHIPBILLNO,SHIPBILLDATE,PORTCODE,FILENO,INVSERIALNO,INVNO,INVDATE,FOBCURRCODE,FOBAMT,FRIEGHTCURRCODE,FRIEGHTAMT,INSCURRCODE,INSAMT,COMMCURRCODE,COMMAMT,DISCURRCODE,DISAMT,DEDCURRCODE,DEDAMT,PKGCURRCODE,PKGAMT) values(?,?,?,?,?,?,TO_DATE(?, 'DD-MM-YYYY'),?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

  public static final String INS_TEMP_EDI_INV_DATA = "INSERT INTO ETT_TEMP_EDPMS_SHP_INV(SHIPBILLNO,SHIPBILLDATE,PORTCODE,FILENO, INVSERIALNO,INVNO,INVDATE,FOBCURRCODE,FOBAMT,FRIEGHTCURRCODE,FRIEGHTAMT,INSCURRCODE, INSAMT,COMMCURRCODE,COMMAMT,DISCURRCODE,DISAMT,DEDCURRCODE,DEDAMT,PKGCURRCODE,PKGAMT)  SELECT SHIPBILLNO,SHIPBILLDATE,PORTCODE,FILENO, INVSERIALNO,INVNO,INVDATE,FOBCURRCODE,FOBAMT,FRIEGHTCURRCODE,FRIEGHTAMT,INSCURRCODE, INSAMT,COMMCURRCODE,COMMAMT,DISCURRCODE,DISAMT,DEDCURRCODE,DEDAMT,PKGCURRCODE,PKGAMT FROM ETT_EDPMS_SHP_INV WHERE  SHIPBILLNO=? AND SHIPBILLDATE=? AND PORTCODE=? AND INVSERIALNO=? AND INVNO=? ";

  public static final String UPDATE_EDI_INV_DATA = "UPDATE ETT_EDPMS_SHP_INV SET INVDATE=TO_DATE(?, 'DD-MM-YYYY'), FOBCURRCODE=?,FOBAMT=?,FRIEGHTCURRCODE=?,FRIEGHTAMT=?,INSCURRCODE=?,INSAMT=?, COMMCURRCODE=?,COMMAMT=?,DISCURRCODE=?,DISAMT=?,DEDCURRCODE=?,DEDAMT=?,PKGCURRCODE=?,PKGAMT=?,FILENO=? WHERE  SHIPBILLNO=? AND SHIPBILLDATE=? AND PORTCODE=? AND INVSERIALNO=? AND INVNO=? ";

  public static final String GET_SOFTEX_SHIP_VALUE = "SELECT NVL(RECIND,'1') AS RECIND FROM ETT_EDPMS_SHP_SOFTEX WHERE SHIPBILLDATE =? AND PORTCODE=? AND FORMNO=?";

  public static final String GET_SOFTEX_SHIP_INV_VALUE = "SELECT COUNT(*) AS COUNT FROM ETT_EDPMS_SHP_INV_SOFTEX WHERE SHIPBILLDATE =? AND PORTCODE=? AND FORMNO=? AND INVSERIALNO=? AND INVNO=? ";

  public static final String INS_SHP_SOFTEX_DATA = "INSERT INTO ETT_EDPMS_SHP_SOFTEX(SHIPBILLDATE,PORTCODE,LEODATE,CUSTNO,FORMNO,IECODE,ADCODE,EXPORTAGENCY,EXPORTTYPE,RECIND,COUNTRYDEST,FILENO)values(?,?,TO_DATE(?, 'DD-MM-YYYY'),?,?,?,?,?,?,?,?,?)";

  public static final String INS_TEMP_SHP_SOFTEX_DATA = "INSERT INTO ETT_TEMP_EDPMS_SHP_SOFTEX(SHIPBILLDATE,LEODATE,CUSTNO,FORMNO,IECODE,ADCODE,PORTCODE,EXPORTAGENCY,EXPORTTYPE,RECIND,COUNTRYDEST,FILENO)SELECT SHIPBILLDATE,LEODATE,CUSTNO,FORMNO,IECODE,ADCODE,PORTCODE,EXPORTAGENCY,EXPORTTYPE,RECIND,COUNTRYDEST,FILENO FROM ETT_EDPMS_SHP_SOFTEX WHERE  SHIPBILLDATE=? AND PORTCODE=? AND FORMNO=?";

  public static final String UPDATE_SHP_SOFTEX_DATA = "UPDATE ETT_EDPMS_SHP_SOFTEX SET LEODATE=TO_DATE(?, 'DD-MM-YYYY'), CUSTNO=?, IECODE=?,ADCODE=?,EXPORTAGENCY=?,EXPORTTYPE=?,RECIND=?,COUNTRYDEST=?,FILENO=? WHERE  SHIPBILLDATE=? AND PORTCODE=? AND FORMNO=?";

  public static final String UPDATE_SHP_SOFTEX_CAN_DATA = "UPDATE ETT_EDPMS_SHP_SOFTEX SET RECIND=?,FILENO=? WHERE  SHIPBILLDATE=? AND PORTCODE=? AND FORMNO=? ";

  public static final String INS_INV_SOFTEX_DATA = "INSERT INTO ETT_EDPMS_SHP_INV_SOFTEX(SHIPBILLDATE,PORTCODE,FORMNO,FILENO,INVSERIALNO,INVNO,INVDATE,FOBCURRCODE,FOBAMT,FRIEGHTCURRCODE,FRIEGHTAMT,INSCURRCODE,INSAMT,COMMCURRCODE,COMMAMT,DISCURRCODE,DISAMT,DEDCURRCODE,DEDAMT,PKGCURRCODE,PKGAMT) values(?,?,?,?,?,?,TO_DATE(?, 'DD-MM-YYYY'),?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

  public static final String INS_TEMP_INV_SOFTEX_DATA = "INSERT INTO ETT_TEMP_EDPMS_SHP_INV_SOFTEX(SHIPBILLDATE,PORTCODE,FORMNO,FILENO, INVSERIALNO,INVNO,INVDATE,FOBCURRCODE,FOBAMT,FRIEGHTCURRCODE,FRIEGHTAMT,INSCURRCODE, INSAMT,COMMCURRCODE,COMMAMT,DISCURRCODE,DISAMT,DEDCURRCODE,DEDAMT,PKGCURRCODE,PKGAMT)  SELECT SHIPBILLDATE,PORTCODE,FORMNO,FILENO, INVSERIALNO,INVNO,INVDATE,FOBCURRCODE,FOBAMT,FRIEGHTCURRCODE,FRIEGHTAMT,INSCURRCODE, INSAMT,COMMCURRCODE,COMMAMT,DISCURRCODE,DISAMT,DEDCURRCODE,DEDAMT,PKGCURRCODE,PKGAMT FROM ETT_EDPMS_SHP_INV_SOFTEX WHERE  SHIPBILLDATE=? AND PORTCODE=? AND FORMNO=? AND INVSERIALNO=? AND INVNO=? ";

  public static final String UPDATE_INV_SOFTEX_DATA = "UPDATE ETT_EDPMS_SHP_INV_SOFTEX SET INVDATE=TO_DATE(?, 'DD-MM-YYYY'), FOBCURRCODE=?,FOBAMT=?,FRIEGHTCURRCODE=?,FRIEGHTAMT=?,INSCURRCODE=?,INSAMT=?, COMMCURRCODE=?,COMMAMT=?,DISCURRCODE=?,DISAMT=?,DEDCURRCODE=?,DEDAMT=?,PKGCURRCODE=?,PKGAMT=?,FILENO=? WHERE  SHIPBILLDATE=? AND PORTCODE=? AND FORMNO=? AND INVSERIALNO=? AND INVNO=? ";

  public static final String TABLE_ETT_TRR_SHP_ACK_STG = "ETT_TRR_SHP_ACK_STG";
 
public static final String GET_TRR_FILE_NAME = "SELECT FILE_NAME FROM ETT_TRR_ACK_Files WHERE FILE_NAME=?";

  public static final String INS_ETT_TRR_ACK_FILES = "INSERT INTO ETT_TRR_ACK_FILES(FILE_NO,NO_OF_SHIPPING_BILLS,FILE_NAME,STATUS,PROCESSED_DATE) values(?,?,?,?,TO_DATE(?,'DD-MM-YYYY'))";

  public static final String GET_TRR_SHIP_VALUE = "SELECT ERRORCODE FROM ETT_TRR_SHP_ACK_STG WHERE SHIPPINGBILLNO=? AND SHIPPINGBILLDATE=? AND PORTCODE=?";

  public static final String INS_TRR_XML_DATA = "INSERT INTO ETT_TRR_SHP_ACK_STG(PORTCODE,EXPORTAGENCY,EXPORTTYPE,SHIPPINGBILLNO,SHIPPINGBILLDATE,FORMNO,IECODE,EXISTINGADCODE,NEWADCODE,FILE_NO,ERRORCODE) values(?,?,?,?,?,?,?,?,?,?,?)";

  public static final String TABLE_ETT_WSN_SHP_ACK_STG = "ETT_WSN_SHP_ACK_STG";

  public static final String GET_WSN_FILE_NAME = "SELECT FILE_NAME FROM ETT_WSN_ACK_FILES WHERE FILE_NAME=?";

  public static final String INS_ETT_WSN_ACK_FILES = "INSERT INTO ETT_WSN_ACK_FILES(FILE_NO,NO_OF_SHIPPING_BILLS,NO_OF_INVOICES,FILE_NAME,STATUS,PROCESSED_DATE) values(?,?,?,?,?,TO_DATE(?,'DD-MM-YYYY'))";

  public static final String GET_WSN_SHIP_VALUE = "SELECT ERRORCODES FROM ETT_WSN_SHP_ACK_STG WHERE SHIPPINGBILLNO=? AND SHIPPINGBILLDATE=? AND PORTCODE=? AND RECORDINDICATOR=? ";

  public static final String INS_WSN_XML_DATA = "INSERT INTO ETT_WSN_SHP_ACK_STG(PORTCODE,EXPORTTYPE,RECORDINDICATOR,SHIPPINGBILLNO,SHIPPINGBILLDATE,FORMNO,LEODATE,ADCODE,PORTDISCHARGE,BOENO,BOEDATE,SHIPMENTINDICATOR,WRT_SEQNO,FILE_NO,ERRORCODES) values(?,?,?,?,?,?,TO_DATE(?, 'DD-MM-YYYY'),?,?,?,TO_DATE(?, 'DD-MM-YYYY'),?,?,?,?)";

  public static final String GET_WSN_INV_VALUE = "SELECT INVOICESERIALNO,INVOICENO FROM ETT_WSN_SHP_INV_ACK_STG WHERE INVOICESERIALNO=? AND INVOICENO=?";

  public static final String INS_ETT_WSN_SHP_INV_ACK_STG = "INSERT INTO ETT_WSN_SHP_INV_ACK_STG(INVOICESERIALNO,INVOICENO,INVOICEDATE,WRITEOFFINDICATOR,WRITEOFFAMOUNT,WRITEOFFDATE,CLOSEOFBILLINDICATOR,FILE_NO,SHIPPINGBILLNO,SHIPPINGBILLDATE,PORTCODE,FORMNO,INVOICEERRORCODES) values(?,?,TO_DATE(?, 'DD-MM-YYYY'),?,?,TO_DATE(?, 'DD-MM-YYYY'),?,?,?,?,?,?,?)";

  public static final String UPDATE_REAL_SHP_TBL = "UPDATE ETT_GR_SHP_TBL SET REALIZATIONAMOUNT=?, REALIZATIONCURR=?,  WRITEOFFAMOUNT=?, WRITEOFFDATE=TO_DATE(?, 'DD-MM-YYYY'), EXCHANGERATE=? , RSTATUS=? , LASTUPDATE =to_timestamp(?, 'DD-MM-YYYY HH12:MI:SS'),USERID=?,PAY_SERIAL_NO=? WHERE  BILLREFNO=? AND EVENTREFNO=? AND SHIPBILLNO=? AND SHIPBILLDATE=? AND PORTCODE=?";

  public static final String INSERT_GR_REL_SHP_TBL = "INSERT INTO ETT_GR_REL_SHP_TBL (BILLREFNO,EVENTREFNO, PAY_SERIAL_NO, SHIPBILLNO, SHIPBILLDATE, PORTCODE,FORMNO,SHIPPINGBILLAMOUNT,SHIPPINGBILLCURR,REALIZATIONAMOUNT, REALIZATIONCURR,REALIZATONDATE,PAY_SEQNO,INWARDNO,FIRCNO,REM_ADCODE,PAY_PARTY, WRITEOFFAMOUNT,WRITEOFFDATE,EXCHANGERATE,BANKCHRGS,BOENO,BOEDATE,PORTDISCHARGE,RSTATUS,USERID,CREATEDON) VALUES (?,?,?,?,?,?,?,?,?,?,?,TO_DATE(?, 'DD-MM-YYYY'),?,?,?,?,?, ?,TO_DATE(?, 'DD-MM-YYYY'),?,?,?,TO_DATE(?, 'DD-MM-YYYY'),?,?,?,SYSTIMESTAMP)";

  public static final String GET_FIRC_DETAILS = " SELECT DECODE(TRIM(FIRC.FIRC_REG_STATUS),'YES',FIRC.FIRC_ADCODE,EXTBR.ADCODE)  AS ADCODE, FIRC.TRANS_REF_NO AS TRANS_REF_NO,DECODE(TRIM(FIRC.FIRC_REG_STATUS),'YES',FIRC.FIRC_TRANSFER_NO,FRD.FRNUMB) AS FIRC_SERIAL_NO, DECODE(TRIM(FIRC.FIRC_REG_STATUS),'YES',FIRC.REM_DATE,FIRC.VALUE_DATE) AS FIRC_DATE,FRD.FIRCCU AS FIRC_CUR,FRD.FRCUTA AS FIRC_UTLAMT FROM MASTER MAS,BASEEVENT BEV,EXTEVENTFRD FRD,EXTBRAMAS EXTBR, EXTEVENT EXT,C8PF C82,ETT_FIRC_LODGEMENT FIRC  WHERE MAS.KEY97 = BEV.MASTER_KEY AND BEV.STATUS     IN ('i','c') AND TRIM(FRD.FIRCCU)   = TRIM(C82.C8CCY ) AND TRIM(BEV.KEY97) = TRIM(EXT.EVENT)  AND EXT.KEY29 = FRD.FK_EVENT AND MAS.BHALF_BRN = EXTBR.BCODE (+) AND TRIM(FIRC.FIRC_SERIAL_NO) = TRIM(FRD.FRNUMB) AND TRIM(MAS.MASTER_REF)  = TRIM(?)  AND TRIM(FRD.FIRCEVE) = TRIM(?)";

  public static final String GET_FIRC_COUNT = " SELECT COUNT(*) AS IRM_COUNT FROM MASTER MAS,BASEEVENT BEV,EXTEVENTFRD FRD,EXTBRAMAS EXTBR, EXTEVENT EXT,C8PF C82,ETT_FIRC_LODGEMENT FIRC  WHERE MAS.KEY97 = BEV.MASTER_KEY AND BEV.STATUS     IN ('i','c') AND TRIM(FRD.FIRCCU)   = TRIM(C82.C8CCY ) AND TRIM(BEV.KEY97) = TRIM(EXT.EVENT)  AND EXT.KEY29 = FRD.FK_EVENT AND MAS.BHALF_BRN = EXTBR.BCODE (+) AND TRIM(FIRC.FIRC_SERIAL_NO) = TRIM(FRD.FRNUMB) AND TRIM(MAS.MASTER_REF)  = TRIM(?)  AND TRIM(FRD.FIRCEVE) = TRIM(?)";

  public static final String GET_SHP_REL_DETAILS = "SELECT INWARDNO,FIRCNO,SHIPPINGBILLAMOUNT,REALIZATIONAMOUNT,BANKCHRGS, TO_CHAR(TO_DATE(REALIZATONDATE,'DD-MM-YY'),'DD-MM-YYYY') AS REALIZATONDATE  FROM  ETT_GR_REL_SHP_TBL WHERE BILLREFNO =? AND EVENTREFNO = ? AND PAY_SERIAL_NO =?  AND SHIPBILLNO=? AND  SHIPBILLDATE=? AND PORTCODE=? ";

  public static final String UPDATE_REAL_INV_TBL = "UPDATE ETT_GR_INV_TBL SET REALIZATIONCURRCODE=?,REALIZATIONDATE=TO_DATE(?, 'DD-MM-YY'),CURREXRATE=?, RFOBAMTIC=?, RFREIGHTAMTIC=?, RINSURANCEAMTIC=?, RFOBAMT=?, RFREIGHTAMT=?, RINSURANCEAMT=?, REALIZATIONSTATUS=?, CLOSEOFBILLIND=?, SHIPMENTIND=?, WRITEOFIND=?, WRITEOFINDAMOUNT=?, WRITEOFDATE=TO_DATE(?, 'DD-MM-YY'),WRITEOFFSTATUS=?,RSTATUS=?,LASTUPDATE =to_timestamp(?, 'DD-MM-YYYY HH12:MI:SS'),USERID=?,PAY_SERIAL_NO=? WHERE BILLREFNO=? AND EVENTREFNO=? AND INVSERIALNO=? AND INVNO=? AND  SHIPBILLNO=? AND SHIPBILLDATE=? AND PORTCODE=?";

  public static final String INSERT_GR_REL_INV_TBL = "INSERT INTO ETT_GR_REL_INV_TBL (BILLREFNO,EVENTREFNO, PAY_SERIAL_NO, SHIPBILLNO, SHIPBILLDATE, PORTCODE,INVSERIALNO,INVNO,INVDATE, FOBAMT,FRIEGHTAMT,INSAMT, REALIZATIONDATE,REALIZATIONCURRCODE,CLOSEOFBILLIND, REALIZATIONSTATUS,RFOBAMTIC,RFREIGHTAMTIC,RINSURANCEAMTIC, RFOBAMT,RFREIGHTAMT,RINSURANCEAMT, CURREXRATE,SHIPMENTIND,WRITEOFINDAMOUNT,WRITEOFFSTATUS,WRITEOFDATE,WRITEOFIND,RSTATUS,USERID,CREATEDON,INWARDNO,FIRCNO,BANKCHRGS) VALUES (?,?,?,?,?,?,?,?,TO_DATE(?, 'DD-MM-YYYY'),?,?,?,TO_DATE(?, 'DD-MM-YYYY'),?,?,?,?,?,?,?,?,?,?,?,?,?,TO_DATE(?, 'DD-MM-YY'),?,?,?,SYSTIMESTAMP,?,?,?)";

  public static final String FETCH_RODACK_VALUE = "SELECT * FROM ETT_SHP_ROD_ACK_STG";

  public static final String FETCH_PENACK_VALUE = "SELECT * FROM ETT_PEN_SHP_ACK_STG";

  public static final String FETCH_TRRACK_VALUE = "SELECT * FROM ETT_TRR_SHP_ACK_STG";

  public static final String CUST_LIST = "SELECT * FROM GFPF WHERE GFCUN = GFCUN";

  public static final String GET_RODACK_VALUE = "SELECT PORTCODE,EXPORTTYPE,RECORDINDICATOR,SHIPPINGBILLNO,SHIPPINGBILLDATE, FORMNO,TO_CHAR(TO_DATE(LEODATE,'DD-MM-YY'),'DD-MM-YY') AS LEODATE,IECODE,CHANGEDIECODE,ADCODE,ADEXPORTAGENCY,DIRECTDISPATCHINDICATOR,ADBILLNO, TO_CHAR(TO_DATE(DATEOFNEGOTIATION,'DD-MM-YY'),'DD-MM-YY') AS DATEOFNEGOTIATION,BUYERNAME,BUYERCOUNTRY,FILE_NO,ERRORCODES FROM ETT_SHP_ROD_ACK_STG  WHERE SHIPPINGBILLDATE=? AND PORTCODE=? ";

  public static final String UPDATE_EDPMS_CANCEL_PARENT = "UPDATE ETT_PRN_SHP_ACK_STG SET STATUS = ?, USERID = ?, UPDTIME = SYSTIMESTAMP WHERE TRIM(GR_NUMBER) = ?";

  public static final String UPDATE_EDPMS_CANCEL_CHILD = "UPDATE ETT_PRN_SHP_INV_ACK_STG SET STATUS = ? WHERE GR_SHP_NO = ?";

  public static final String UPDATE_EDPMS_REL_SHP_BANK_CHARGES = "UPDATE ETT_GR_REL_SHP_TBL SET PAYMENT_SEQNO = ETT_GR_REL_SHP_SEQ_NO,BANKCHRGS = ?,RSTATUS = 'N' WHERE PAYMENT_SEQNO = ?";

  public static final String UPDATE_EDPMS_REL_INV_BANK_CHARGES = "UPDATE ETT_GR_REL_INV_TBL SET RSTATUS = 'N', BANKCHRGS = (SELECT ?/CNT FROM (SELECT COUNT(1) CNT FROM ETT_GR_REL_INV_TBL WHERE GRSHPNO IN (SELECT ETT_GR_REL_SHP_TBL.GRNUMBER FROM ETT_GR_REL_SHP_TBL WHERE PAYMENT_SEQNO = ?))) WHERE GRSHPNO = (SELECT GRNUMBER FROM ETT_GR_REL_SHP_TBL WHERE PAYMENT_SEQNO = ?)";

  public static final String INS_EDPMS_ERR_TMP_TBL = "INSERT INTO ETT_EDPMS_ERR_TMP_TBL(SHIPBILLNO, SHIPBILLDATE, PORTCODE, FORMNO, INVNO, INVSERIALNO, SHP_ERROR_MSG, INV_ERROR_MSG, FILENO) VALUES( ?, ?, ?, ?, ?, ?, ?, ?, ?)";

  public static final String INS_EDPMS_ERR_REC3_ERR = "INSERT INTO ETT_EDPMS_ERR_TMP_TBL(SHIPBILLNO, SHIPBILLDATE, PORTCODE, FORMNO, SHP_ERROR_MSG,  FILENO) VALUES(?, ?, ?, ?, ?, ?)";

  public static final String SELECT_ERROR_LIST = "SELECT BILLNO, BILLDATE, PCODE, FORMNO, INVSERNO, INVNO, SHP||','||INV ERROR_CODE FROM(SELECT TMP.SHIPBILLNO BILLNO, TMP.SHIPBILLDATE BILLDATE, TMP.PORTCODE PCODE, TMP.FORMNO FORMNO, TMP.INVSERIALNO INVSERNO, TMP.INVNO INVNO, TMP.SHP_ERROR_MSG SHP, TMP.INV_ERROR_MSG INV FROM ETT_EDPMS_ERR_TMP_TBL TMP, ETT_EDPMS_FILES F WHERE TMP.FILENO   = F.FILENO AND F.FILENAME     = ? AND SHP_ERROR_MSG IS NOT NULL )";

  public static final String COUNT_ERROR_RECORD = "SELECT COUNT(1) AS CNT FROM ETT_BOE_DETAILS_TEMP_STG\tWHERE FILENO = ? AND ERROR_CODE IS NOT NULL";

  public static final String SELECT_FILE_LIST = "SELECT FILENO, FILENAME FROM ETT_IDPMS_FILES WHERE FILENAME LIKE '%?%' ORDER BY FILENAME ASC";

  public static final String COUNT_FILE_EXIST = "SELECT COUNT(1) AS CNT FROM ETT_IDPMS_FILES WHERE FILENAME LIKE '%?%'";
 
public static final String COUNT_SHP_STATUS = "SELECT COUNT(DISTINCT(SHP.SHIPBILLNO)) SHPCOUNT, COUNT(INV.INVNO) INVCOUNT FROM ETT_EDPMS_SHP SHP, ETT_EDPMS_SHP_INV INV WHERE SHP.FILENO = ? AND SHP.FILENO = INV.FILENO AND SHP.SHIPBILLNO = INV.SHIPBILLNO";

  public static final String COUNT_SOFT_STATUS = "SELECT COUNT(DISTINCT(SOFT.FORMNO)) FORMNO, COUNT(INVNO) INVNO FROM ETT_EDPMS_SHP_SOFTEX SOFT, ETT_EDPMS_SHP_INV_SOFTEX INVSOFT WHERE SOFT.FILENO = ? AND SOFT.FILENO = INVSOFT.FILENO AND SOFT.FORMNO = INVSOFT.FORMNO";

  public static final String COUNT_PRN_STATUS = "SELECT COUNT(DISTINCT(PRNSHP.SHIPPINGBILLNO)) SHPCOUNT,  COUNT(PRNINV.INVOICENO) INVCOUNT FROM ETT_PRN_SHP_ACK_STG PRNSHP, ETT_PRN_SHP_INV_ACK_STG PRNINV WHERE PRNSHP.FILE_NO   = ? AND PRNSHP.FILE_NO = PRNINV.FILE_NO AND PRNSHP.SHIPPINGBILLNO = PRNINV.SHIPPINGBILLNO";

  public static final String DELETE_SHIPPING_RECORDS = "DELETE FROM ETT_EDPMS_SHP WHERE SHIPBILLNO = ? AND TO_DATE(SHIPBILLDATE,'DD/MM/YYYY') = TO_DATE(?,'DD/MM/YYYY') AND PORTCODE = ? AND FILENO = ?";

  public static final String DELETE_SHIPPING_INV_RECORDS = "DELETE FROM ETT_EDPMS_SHP_INV WHERE SHIPBILLNO = ? AND TO_DATE(SHIPBILLDATE,'DD/MM/YYYY') = TO_DATE(?,'DD/MM/YYYY') AND PORTCODE = ? AND FILENO = ?";

  public static final String COUNT_ERROR_SHP_RECORDS = "SELECT SUM(BILLCOUNT+FORMCOUNT) AS CNT FROM (SELECT COUNT(DISTINCT SHIPBILLNO) AS BILLCOUNT, 0 AS FORMCOUNT FROM ETT_EDPMS_ERR_TMP_TBL WHERE FILENO = ? UNION SELECT 0 AS BILLCOUNT, COUNT(DISTINCT FORMNO) AS FORMCOUNT FROM ETT_EDPMS_ERR_TMP_TBL WHERE FILENO = ?)";

  public static final String DELETE_SHP_SOFTEX_RECORDS = "DELETE FROM ETT_EDPMS_SHP_SOFTEX WHERE TO_DATE(SHIPBILLDATE,'DD/MM/YYYY') = TO_DATE(?,'DD/MM/YYYY') AND PORTCODE = ? AND FORMNO = ? AND FILENO = ?";

  public static final String DELETE_SHP_SOFTEX_INV_RECORDS = "DELETE FROM ETT_EDPMS_SHP_INV_SOFTEX WHERE TO_DATE(SHIPBILLDATE,'DD/MM/YYYY') = TO_DATE(?,'DD/MM/YYYY') AND PORTCODE=? AND FORMNO=? AND FILENO = ?";

  public static final String COUNT_PRN_SUCCESS = "SELECT SUM(SHPCNT+FORMNO), SUM(INVCNT) FROM (SELECT COUNT(DISTINCT SHP.SHIPPINGBILLNO) SHPCNT, COUNT(DISTINCT FORMNO) FORMNO, 0 INVCNT FROM ETT_PRN_SHP_ACK_STG SHP WHERE FILE_NO = ? UNION ALL SELECT 0 SHPCNT, 0 FORMNO, COUNT(INV.INVOICENO) FROM ETT_PRN_SHP_INV_ACK_STG INV WHERE FILE_NO = ?)";

  public static final String SHOW_PRN_FILE_STATUS = "SELECT BILLNO, BILLDATE, PCODE, FORMNO, INVSERNO, INVNO, SHP ||',' ||INV ERROR_CODE FROM(SELECT TMP.SHIPBILLNO BILLNO, TMP.SHIPBILLDATE BILLDATE, TMP.PORTCODE PCODE, TMP.FORMNO FORMNO, TMP.INVSERIALNO INVSERNO, TMP.INVNO INVNO,TMP.SHP_ERROR_MSG SHP,TMP.INV_ERROR_MSG INV FROM ETT_EDPMS_ERR_TMP_TBL TMP,   ETT_PRN_ACK_FILES F WHERE TMP.FILENO   = F.FILE_NO AND F.FILE_NAME     = ? AND SHP_ERROR_MSG IS NOT NULL)";

  public static final String ROD_FAIL_PASS_ERROR_DETAILS = "SELECT  STG.SHIPPINGBILLNO AS BILLNO ,STG.SHIPPINGBILLDATE AS BILLDATE,STG.PORTCODE  AS PCODE ,STG.FORMNO AS FORMNO,  '' AS INVSERNO,'' AS INVNO, ERRORCODES  AS ERROR_CODE FROM ETT_SHP_ROD_ACK_STG STG,ETT_ROD_ACK_FILES FL  WHERE  TRIM(FL.FILE_NO) =TRIM(STG.FILE_NO)  and TRIM(STG.FILE_NO)=?";

  public static final String ROD_AUDIT_TRIAL_INSERT = "INSERT INTO ETT_ROD_AUDIT_TABLE (SHPBILLNO,SHPBILLDATE,PORTCODE,RECORD,EXPTYPE,FORMNO,LOEDATE,IECODE,CIECODE,ADCODE,ADEXPORT,DDINDICATOR,ADBILLNO,DATENEG,BUYERNAME,USERNAME,ROD_SEQ_NO,CREATE_DATE) VALUES (?,TO_DATE(?,'DD-MM-YY'),?,?,?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,?,?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,SYSTIMESTAMP)";

  public static final String IRM_AUDIT_TRIAL_INSERT = "INSERT INTO ETT_IRM_AUDIT_TABLE (TRXN_REFNO,MASTER_REFNO,REM_AMOUNT,REM_DATE,ADCODE,FIRC_FLAG,FIRC_NO,FIRC_DATE,FIRCAMOUNT,CURRENCY,IECODE,IENAME,REM_NAME,REM_ADDR,REM_COUNTRY,REM_BANKNAME,REM_BANKCOUNTRY,SWIFT_REFNO,PURPOSECODE,REC_IND,REMARKS,USERNAME,IRM_SEQ_NO,CREATE_DATE) VALUES (?,?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSTIMESTAMP)";

  public static final String PRN_AUDIT_TRIAL_INSERT = "INSERT INTO ETT_PRN_AUDIT_TABLE (SHPBILLNO,SHPBILLDATE,PORTCODE,FORMNO,LOEDATE,ADCODE,EXPTYPERECORD,BILLREFNO,EVENTREFNO,PAYREFNO,INWARDNO,FIRCNO,REMADCODE,PAYPARTY,REALCURR,REALDATE,EBRCNO,INVSERNO,INVNO,INVDATE,ACCNO,BANKCHGAMT,FOBAMT,FOBCURCODE,FRIAMT,FRICURCODE,INSAMT,INSCURCODE,RENAME,USERNAME,PRN_SEQ_NO,CREATE_DATE) VALUES (?,TO_DATE(?,'DD-MM-YY'),?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,?,?,?,?,?,?,?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,?,?,?,?,?,?,?,?,SYSTIMESTAMP)";

  public static final String PRN_CANCEL_AUDIT_TRIAL_INSERT = "INSERT INTO ETT_PRN_CANCEL_AUDIT_TABLE (SHPBILLNO,SHPBILLDATE,PORTCODE,FORMNO,LOEDATE,ADCODE,EXPTYPE,RECORD,INWARDNO,FIRCNO,REMADCODE,PAYPARTY,REALCURR,REALDATE,EBRCNO,INVSERNO,INVNO,INVDATE,ACCNO,BANKCHGAMT,FOBAMT,FOBCURCODE,FRIAMT,FRICURCODE,INSAMT,INSCURCODE,RENAME,USERNAME,PRN_SEQ_NO,CREATE_DATE) VALUES (?,TO_DATE(?,'DD-MM-YY'),?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,?,?,?,?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,?,?,?,?,?,?,?,?,SYSTIMESTAMP)";

  public static final String PRN_AMEND_AUDIT_TRIAL_INSERT = "INSERT INTO ETT_PRN_AMEND_AUDIT_TABLE (GRNO,SHPBILLNO,SHIPBILLDATE,PORTCODE,FORMNO,LOEDATE,ADCODE,EXPTYPE,RECORD,INWARDNO,FIRCNO,REMADCODE,PAYPARTY,REALCURR,REALDATE,EBRCNO,INVSERNO,INVNO,INVDATE,ACCNO,BANKCHGAMT,FOBAMT,FOBCURCODE,FRIAMT,FRICURCODE,INSAMT,INSCURCODE,RENAME,USERNAME,PRN_SEQ_NO,CREATE_DATE) VALUES (?,?,TO_DATE(?,'DD-MM-YY'),?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,?,?,?,?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,?,?,?,?,?,?,?,?,SYSTIMESTAMP)";

  public static final String WSN1_AUDIT_TRIAL_INSERT = "INSERT INTO ETT_WSN1_AUDIT_TABLE (SHPBILLNO,SHIPBILLDATE,PORTCODE,FORMNO,LOEDATE,ADCODE,EXPTYPE,RECORD,BILLREFNO,PAYREFNO,WRITEOFFSEQNO,SHPIND,BOENO,BOEDATE,PORTDISCHG,INVSERNO,INVNO,INVDATE,WRITEIND,WRITEAMT,WRITEDATE,CLOSEBILL,USERNAME,WSN_SEQ_NO,CREATE_DATE) VALUES (?,TO_DATE(?,'DD-MM-YY'),?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,?,?,?,?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,TO_DATE(?,'DD-MM-YY'),?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,SYSTIMESTAMP)";

  public static final String WSN2_AUDIT_TRIAL_INSERT = "INSERT INTO ETT_WSN2_AUDIT_TABLE (SHPBILLNO,SHIPBILLDATE,PORTCODE,FORMNO,LOEDATE,ADCODE,EXPTYPE,RECORD,BILLREFNO,PAYREFNO,WRITEOFFSEQNO,SHPIND,BOENO,BOEDATE,PORTDISCHG,INVSERNO,INVNO,INVDATE,WRITEIND,WRITEAMT,WRITEDATE,CLOSEBILL,USERNAME,WSN_SEQ_NO,CREATE_DATE) VALUES (?,TO_DATE(?,'DD-MM-YY'),?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,?,?,?,?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,TO_DATE(?,'DD-MM-YY'),?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,SYSTIMESTAMP)";

  public static final String PEN_AUDIT_TRIAL_INSERT = "INSERT INTO ETT_PEN_AUDIT_TABLE (SHPBILLNO,SHIPBILLDATE,PORTCODE,FORMNO,LOEDATE,IECODE,ADCODE,LETTERNO,LETTERDATE,EXPTYPE,RECORD,IND,INDDATE,USERNAME,PEN_SEQ_NO,CREATE_DATE) VALUES (?,TO_DATE(?,'DD-MM-YY'),?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,TO_DATE(?,'DD-MM-YY'),?,?,SYSTIMESTAMP)";

  public static final String TRR_AUDIT_TRIAL_INSERT = "INSERT INTO ETT_TRR_AUDIT_TABLE (SHPBILLNO,SHIPBILLDATE,PORTCODE,IECODE,FORMNO,EXPTYPE,EXPAGNCY,NEWADCODE,EXADCODE,USERNAME,TRR_SEQ_NO,CREATE_DATE) VALUES (?,TO_DATE(?,'DD-MM-YY'),?,?,?,?,?,?,?,?,?,SYSTIMESTAMP)";

  public static final String EBRC_CANCEL_AUDIT_TRIAL_INSERT = "INSERT INTO ETT_EBRC_CANCEL_AUDIT_TABLE (BRCNO,BRCDATE,STATUS,IECODE,EXPNAME,CODEIFSC,BILLID,SHIPNO,SHIPPORT,SHIPDATE,SHIPCURR,SHIPVALUE,REALCURR,REALVALUE,REALDATE,USERNAME,EBRC_SEQ_NO,CREATE_DATE) VALUES (?,TO_DATE(?,'DD-MM-YY'),?,?,?,?,?,?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,?,TO_DATE(?,'DD-MM-YY'),?,?,SYSTIMESTAMP)";

  public static final String EBRC_AUDIT_TRIAL_INSERT = "INSERT INTO ETT_EBRC_AUDIT_TABLE (BRCNO,BRCDATE,STATUS,IECODE,EXPNAME,CODEIFSC,BILLID,SHIPNO,SHIPPORT,SHIPDATE,SHIPCURR,SHIPVALUE,REALCURR,REALVALUE,REALDATE,USERNAME,EBRC_SEQ_NO,CREATE_DATE) VALUES (?,TO_DATE(?,'YYYY-MM-DD'),?,?,?,?,?,?,?,TO_DATE(?,'YYYY-MM-DD'),?,?,?,?,TO_DATE(?,'YYYY-MM-DD'),?,?,SYSTIMESTAMP)";

  public static final String IRFIRC_AUDIT_TRIAL_INSERT = "INSERT INTO ETT_IRFIRC_AUDIT_TABLE (MASTERREFNO,ADCODE,FIRCFLAG,FIRCNO,FIRCDATE,FIRCAMT,RECIND,USERNAME,IRFIRC_SEQ_NO,CREATE_DATE) VALUES (?,?,?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,?,SYSTIMESTAMP)";

  public static final String IREXT_AUDIT_TRIAL_INSERT = "INSERT INTO ETT_IREXT_AUDIT_TABLE (SERIALNO,MASTERREFNO,ADCODE,IECODE,EXTIND,EXTDATE,LETTERNO,LETTERDATE,RECIND,REASON,USERNAME,IREXT_SEQ_NO,CREATE_DATE) VALUES (?,?,?,?,?,TO_DATE(?,'DD-MM-YY'),?,TO_DATE(?,'DD-MM-YY'),?,?,?,?,SYSTIMESTAMP)";

  public static final String IRCLS_CANCEL_AUDIT_TRIAL_INSERT = "INSERT INTO ETT_IRCLS_CANCEL_AUDIT_TABLE (SERIALNO,MASTERREFNO,ADCODE,IECODE,CURRENCY,AMOUNT,APPROVEDBY,LETTERNO,ADJDATE,REASON,DOCNO,DOCDATE,DOCPORT,RECIND,REMARKS,USERNAME,IRCLS_SEQ_NO,CREATE_DATE) VALUES (?,?,?,?,?,?,?,?,TO_DATE(?,'DD-MM-YY'),?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,?,?,SYSTIMESTAMP)";

  public static final String IRCLS_AUDIT_TRIAL_INSERT = "INSERT INTO ETT_IRCLS_AUDIT_TABLE (SERIALNO,MASTERREFNO,ADCODE,IECODE,CURRENCY,AMOUNT,APPROVEDBY,LETTERNO,ADJDATE,REASON,DOCNO,DOCDATE,DOCPORT,RECIND,REMARKS,USERNAME,IRCLS_SEQ_NO,CREATE_DATE) VALUES (?,?,?,?,?,?,?,?,TO_DATE(?,'DD-MM-YY'),?,?,TO_DATE(?,'DD-MM-YY'),?,?,?,?,?,SYSTIMESTAMP)";

}