#************************************************

#**********  DB Information *********************
 
#Localization
 
JNDIConnection = false

#JNDICONTEXT = com.ibm.websphere.naming.WsnInitialContextFactory
 
#IDFC-Prod

#JNDI_PROVIDER_URL = t3://10.1.16.51

#JNDIPORT = 7114

#JNDIZONE = jdbc/zone
 
 
#106

#JNDI_PROVIDER_URL = t3://172.19.36.127

#JNDIPORT = 7004

#JNDIZONE = jdbc/zone
 
#Pre-Prod

#JNDI_PROVIDER_URL = t3://10.5.8.114,10.5.8.115

#JNDIPORT = 7114

#JNDIZONE = jdbc/zone
 
#107

JNDI_PROVIDER_URL = t3://172.19.36.107

JNDIPORT = 7004

JNDIZONE = jdbc/zone
 
 
#DR-Server

#JNDI_PROVIDER_URL = t3://10.5.8.114

#JNDIPORT = 7114

#JNDIZONE = jdbc/zone
 
 
#pre

#JNDI_PROVIDER_URL = t3://tipluspreprod1.idfcbank.com

#JNDIPORT = 7113

#JNDIZONE = jdbc/scfzone
 
 
#Zone3

DriverClass = oracle.jdbc.driver.OracleDriver
 
 
#************************************************

#**********  END DB Information *****************
 
 
 