#------------------------------------------------------------------------------------------------------

# This log4j will create separate file for logs and SystemOut.log file will not write anything.

# Antony, 2018-Nov-12

#------------------------------------------------------------------------------------------------------

##

##------Last Deployment Date:25/07/2020

##

# Root logger option

#It will Write only Info log in Log File

log4j.rootLogger=INFO, file ,stdout
 
# Direct log messages to a log file

log4j.appender.file=org.apache.log4j.RollingFileAppender

#UAT

log4j.appender.file.File=/ftrade/FTI_Repositories/Localisation_logs/Preshipment/Preshipment.log
 
 
#Local test

#log4j.appender.file.File=D:/ETT_LOCALIZATION/ETT_LOC_LOGS/Preshipment/Preshipment.log
 
 
log4j.appender.file.MaxFileSize=10MB

log4j.appender.file.MaxBackupIndex=40

log4j.appender.file.layout=org.apache.log4j.PatternLayout

log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

# Below It will display in Console

# Direct log messages to stdout

log4j.appender.stdout=org.apache.log4j.ConsoleAppender

log4j.appender.stdout.Target=System.out

log4j.appender.stdout.layout=org.apache.log4j.PatternLayout

log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
 
 
##-----CommonMethods.java Line:339 ---changed by Vishnupriya 24-07-20 :INC000004189343-Error to thrown for overutilizing preshipment

##-----PreshipmentDAO.java Line:396 ---changed by Ashwin C 18-06-21 :CRQ000000290808-Negative Preshipment