DROP TABLE "ETT_PRESHIPMENT_APISERVER";

CREATE TABLE "ETT_PRESHIPMENT_APISERVER" 

   (	"SEQUENCE" NUMBER(19,0) NOT NULL ENABLE, 

	"VERSION" TIMESTAMP (6) NOT NULL ENABLE, 

	"SERVICE" VARCHAR2(255 CHAR), 

	"OPERATION" VARCHAR2(255 CHAR), 

	"REQUEST" CLOB, 

	"RESPONSE" CLOB, 

	"COMMENTS" VARCHAR2(1024 CHAR), 

	"SERVER" VARCHAR2(255 CHAR), 

	"UPLOADED" TIMESTAMP (6), 

	"STATUS" VARCHAR2(255 CHAR), 

	"NODE" NUMBER(10,0) DEFAULT 1 NOT NULL ENABLE, 

	"TIME_TAKEN" NUMBER(19,0) DEFAULT 0, 

	"MASREF" VARCHAR2(100 CHAR), 

	"EVENTREF" VARCHAR2(100 CHAR), 

	"REPAYAMT" NUMBER(35,0), 

	"TRANSACT" NUMBER(35,0), 

	"CURR" CHAR(3 BYTE), 

	"CIFCODE" VARCHAR2(155 CHAR),

	"LOAN_REF" VARCHAR2(16)

	 PRIMARY KEY ("SEQUENCE")

  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS

  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE SYSTEM  ENABLE

   )

   DROP TABLE TABLE ETT_PRESHIPMENT;

   CREATE TABLE ETT_PRESHIPMENT 

   (    CIF_CODE VARCHAR2(30 BYTE), 

    VALUE_DATE DATE, 

    PAYMENT_AMOUNT NUMBER(20,2), 

    MAS_REF VARCHAR2(30 BYTE), 

    DISBURSE_DATE VARCHAR2(15 BYTE), 

    DUE_DATE VARCHAR2(15 BYTE), 

    LOAN_AMOUNT NUMBER(20,2), 

    OUT_AMOUNT NUMBER(20,2), 

    REPAY_AMOUNT NUMBER(20,2), 

    STATUS VARCHAR2(20 BYTE), 

    BASEEVENT_KEY97 VARCHAR2(20 BYTE), 

    BASEEVENT1_KEY97 VARCHAR2(20 BYTE), 

    BATCHID VARCHAR2(20 BYTE), 

    INPUT_BRANCH VARCHAR2(20 BYTE), 

    BEHALF_BRANCH VARCHAR2(20 BYTE), 

    PRODUCT VARCHAR2(20 BYTE), 

    EVENT VARCHAR2(20 BYTE),

    CURRENCY VARCHAR2(3 BYTE),

    CREATE_DATE TIMESTAMP (6),

    UPDATE_DATE TIMESTAMP (6),

    CUS_MAS_REF VARCHAR2(20), 

	CUS_EVENT_REF VARCHAR2(20)

   );

   DROP TABLE ETT_REPAYED_LOAN;

   CREATE TABLE ETT_REPAYED_LOAN(MASTER_REF VARCHAR2(20),EVENT_REF VARCHAR2(6),LOAN_REF varchar2(20),REPAYED_AMOUNT decimal(15,0),CCY char(3));

   CREATE TABLE ETT_PRESHIP_ERROR_CODES 

   (	ERROR_CODE VARCHAR2(20 BYTE), 

	ERROR_MSG VARCHAR2(100 BYTE), 

	SCREEN_ID VARCHAR2(20 BYTE)

   )

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('0','Please choose cif code','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('1','Please enter repay mount with currency','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('2','Invalid repay amount','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('3','Please select date','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('4','Invalid date','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('5','Invalid outstanding amount','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('6','Payment and Repayment amount are mismatched','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('7','Please enter currency with Amount','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('8','Invalid Currency','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('9','Outstanding amount and Repay amount are mismatched','PS01');
 
 
#Final Error Codes

REM INSERTING into ETT_PRESHIP_ERROR_CODES

SET DEFINE OFF;

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('0','Please choose cif code','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('1','Please enter repay mount with currency','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('2','Invalid repay amount','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('3','Please select date','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('4','Invalid date','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('5','Invalid outstanding amount','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('6','Payment and Repayment amount are mismatched','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('7','Please enter currency with Amount','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('8','Invalid Currency','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('9','Outstanding amount and Repay amount are mismatched','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('0','Please choose cif code','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('1','Please enter repay mount with currency','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('2','Invalid repay amount','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('3','Please select date','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('4','Invalid date','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('5','Invalid outstanding amount','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('6','Payment and Repayment amount are mismatched','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('7','Please enter currency with Amount','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('8','Invalid Currency','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('9','Outstanding amount and Repay amount are mismatched','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('10','Please Choose Product Sub Type','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('11','Repay Amount Mis-Match','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('12','Value Date Cannot be Greater than Processing Date','PS01');

Insert into ETT_PRESHIP_ERROR_CODES (ERROR_CODE,ERROR_MSG,SCREEN_ID) values ('13','Value Date Cannot be Less than Loan start Date','PS01');
 
 
    CREATE SEQUENCE  PRESHIPMENT_SEQNO  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;

    CREATE SEQUENCE  PRESHIPMENT_SEQNO2  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;

    CREATE SEQUENCE  PRESHIPMENT_XKEY  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;


    #11206179    cifCode=11206179&masterRef=12345&eventRef=7890&amount=10000.65INR
 