package in.co.FIRC.utility;

import java.util.Collections;
import java.util.Map;
 
public abstract interface ActionConstants
{
  public static final String SYSTEM = "SYSTEM";
  public static final String Reserved = "R";
  public static final String PENDING = "P";
  public static final String APPROVED = "A";
  public static final String CANCELLED = "C";
  public static final String TR = "TR";
  public static final String TP = "TP";
  public static final String TC = "TC";
  public static final String RN = "RN";
  public static final String RC = "RC";
  public static final String APPROVE = "approve";
  public static final String REJECT = "reject";
  public static final String REJECT1 = "REJECTED";
  public static final String ENTERING_METHOD = "Entering Method";
  public static final String EXITING_METHOD = "Exiting Method";
  public static final String Y = "Y";
  public static final String N = "N";
  public static final String YES = "YES";
  public static final String NO = "NO";
  public static final String TRUE = "true";
  public static final String FALSE = "false";
  public static final String ZERO = "ZERO";
  public static final String REDIRECT = "redirect";
  public static final String ONE = "1";
  public static final String TWO = "2";
  public static final String THREE = "3";
  public static final String FOUR = "4";
  public static final String MAKER_CHECKER = "both";
  public static final String COLUMN_FILE_NAME = "FILE_NAME";
  public static final String COLUMN_STATUS = "STATUS";
  public static final String COLUMN_REFERENCE_NUMBER = "REFERENCE_NUMBER";
  public static final String IS_DATA_AVAILABLE_TWO_CONDITIONS = "SELECT COUNT(1) FROM  TABLE_NAME  WHERE COLUMN_NAME1=? AND COLUMN_NAME2=?";
  public static final String SELECT = "select";
  public static final String SUCCESS = "success";
  public static final String SUBMIT = "submit";
  public static final String DELETE = "delete";
  public static final String COLUMN_SWIFT_NUMBER = "SWIFT_NUMBER";
  public static final String FAIL = "fail";
  public static final String NOS_MAKER = "NostroMaker";
  public static final String NOS_CHECKER = "NostroChecker";
  public static final String MAKER = "maker";
  public static final String CHECKER = "checker";
  public static final String VIEWER = "viewer";
  public static final CharSequence TABLE_NAME = "TABLE_NAME";
  public static final CharSequence COLUMN_NAME1 = "COLUMN_NAME1";
  public static final CharSequence COLUMN_NAME2 = "COLUMN_NAME2";
  public static final String EMPTY = "";
  public static final String FIRC_ISS_SUCCESS = "ISSUANCE FORM IS SUCCESSFULLY SUBMITTED";
  public static final String FIRC_ISS_FAILED = "ISSUANCE FORM IS FAILED";
  public static final String IRM_EXT_SUCCESS = "IRM Extension Succesfully Submitted";
  public static final String IRM_CLOSE_SUCCESS = "IRM Adjustment/Closure Succesfully Submitted";
  public static final String FETCH_MODE = "fetch";
  public static final String VAL_MODE = "validate";
  public static final String INSERT_MODE = "insert";
  public static final String PRINT = "print";
  public static final String DUP_PRINT = "duplicatePrint";
  public static final String BILL_FETCH_MODE = "billfetch";
  public static final String PUR_REDIRECT = "purposecode";
  public static final String CUR_CODE = "currency";
  public static final String PUR_CODE = "purposecode";
  public static final String COUNTRY = "country";
  public static final String CUSTOMER = "customer";
  public static final String FIRC_CHECKER = "FIRCCHECKER";
  public static final String FIRC_MAKER = "FIRCMAKER";
  public static final String FIRC = "FIRC";
  public static final String FIRA = "FIRA";
  public static final GetOptPath path = new GetOptPath();
  public static final String FILE_LOCATION = path.fileLoc("FIRC");
  public static final Map<String, String> TRANS_STATUS = Collections.unmodifiableMap(new ActionConstants.1());
  public static final Map<String, String> CURRENCY_TYPE = Collections.unmodifiableMap(new ActionConstants.2());
  public static final Map<String, String> BANK_NAME = Collections.unmodifiableMap(new ActionConstants.3());
  public static final Map<String, String> LIST_CUSTOMER = Collections.unmodifiableMap(new ActionConstants.4());
  public static final Map<String, String> EX_IND = Collections.unmodifiableMap(new ActionConstants.5());
  public static final Map<String, String> REC_IND = Collections.unmodifiableMap(new ActionConstants.6());
  public static final Map<String, String> CLOSE_IND = Collections.unmodifiableMap(new ActionConstants.7());
  public static final Map<String, String> REASON_ADJ = Collections.unmodifiableMap(new ActionConstants.8());
  public static final Map<String, String> INWARD_TYPE = Collections.unmodifiableMap(new ActionConstants.9());
  public static final Map<String, String> IRM_STATUS = Collections.unmodifiableMap(new ActionConstants.10());
}
