package in.co.ebrc.utility;

import java.util.Collections;
import java.util.Map;
 
public abstract interface ActionConstants
{
  public static final String MT_103 = "103";
  public static final String MT_202 = "202";
  public static final String MT_940 = "940";
  public static final String MT_192 = "192";
  public static final String MT_292 = "292";
  public static final String AutoMapping = "A";
  public static final String SYSTEM = "SYSTEM";
  public static final String ManualMapping = "M";
  public static final String To_BE_MANUAL_MAPPING = "TM";
  public static final String Reserved = "R";
  public static final String PENDING = "P";
  public static final String TR = "TR";
  public static final String TP = "TP";
  public static final String APPROVE = "approve";
  public static final String REJECT = "reject";
  public static final String REJECT1 = "REJECTED";
  public static final String ENTERING_METHOD = "Entering Method";
  public static final String EXITING_METHOD = "Exiting Method";
  public static final String Y = "Y";
  public static final String N = "N";
  public static final String FALSE = "false";
  public static final String initialFileLocation = "C:/nostro_files/first";
  public static final String tempFileLocation = "C:/nostro_files/second";
  public static final String t1FileLocation = "C:/nostro_files/third";
  public static final GetOptPath path = new GetOptPath();
  public static final String FileLocationEBRC = path.Ebrc("EBRC");
  public static final String FileLocation = path.fileLoc("EBRC_IFSC");
  public static final String File_Location = path.Ebrccancel("EBRC_CANCEL");
  public static final CharSequence TABLE_NAME = "TABLE_NAME";
  public static final CharSequence COLUMN_NAME1 = "COLUMN_NAME1";
  public static final CharSequence COLUMN_NAME2 = "COLUMN_NAME2";
  public static final String TABLE_ETT_NOSTRO_UTILITY_MT103 = "ETT_NOSTRO_UTILITY_MT103";
  public static final String TABLE_ETT_NOSTRO_UTILITY_MT940 = "ETT_NOSTRO_UTILITY_MT940";
  public static final String TABLE_ETT_NOSTRO_UTILITY_MT202 = "ETT_NOSTRO_UTILITY_MT202";
  public static final String TABLE_NOSTRO_UTILITY_MATCH = "NOSTRO_UTILITY_MATCH";
  public static final String COLUMN_FILE_NAME = "FILE_NAME";
  public static final String COLUMN_STATUS = "STATUS";
  public static final String COLUMN_REFERENCE_NUMBER = "REFERENCE_NUMBER";
  public static final String COLUMN_SWIFT_NUMBER = "SWIFT_NUMBER";
  public static final String FAIL = "fail";
  public static final String NOS_MAKER = "NostroMaker";
  public static final String NOS_CHECKER = "NostroChecker";
  public static final String MAKER = "maker";
  public static final String CHECKER = "checker";
  public static final String AUDIT_ACTION_ONE = "1";
  public static final String AUDIT_ACTION_TWO = "2";
  public static final String AUDIT_ACTION_THREE = "3";
  public static final String AUDIT_ACTION_FOUR = "4";
  public static final String AUDIT_ACTION_FIVE = "5";
  public static final String AUDIT_ACTION_SIX = "6";
  public static final String AUDIT_ACTION_SEVEN = "7";
  public static final String AUDIT_ACTION_EIGHT = "8";
  public static final String AUDIT_ACTION_NINE = "9";
  public static final String AUDIT_ACTION_TEN = "10";
  public static final String AUDIT_ACTION_ELEVAN = "11";
  public static final String AUDIT_ACTION_TEWLE = "12";
  public static final String AUDIT_ACTION_THEIRTEEN = "13";
  public static final String YES = "YES";
  public static final String OP = "O";
  public static final String FRESH = "F";
  public static final Map<String, String> REC_IND = Collections.unmodifiableMap(new ActionConstants.1());
  public static final Map<String, String> REC_IND1 = Collections.unmodifiableMap(new ActionConstants.2());
  public static final Map<String, String> REC = Collections.unmodifiableMap(new ActionConstants.3());
}