#UAT 2 Server

#DriverClass=oracle.jdbc.driver.OracleDriver

#Url=jdbc:oracle:thin:@10.10.19.179:1528:orcl2

#UserName=TIZONE

#Password=tizone_1234
 
#KOTAK-UAT3

#DriverClass=oracle.jdbc.driver.OracleDriver

#Url=jdbc:oracle:thin:@10.10.20.137:1530/orcl

#UserName=TIZONE

#Password=tizone_1234
 
## PREPRODUCTION

#DriverClass=oracle.jdbc.driver.OracleDriver

#Url=jdbc:oracle:thin:@10.10.7.211:1530/tiplusdb

#UserName=TIZONE

#Password=Tm!#An59
 
 
#UAT2 Server

#DriverClass=oracle.jdbc.driver.OracleDriver

#Url=jdbc:oracle:thin:@10.10.7.211:1532:tireport

#UserName=TIZONE

#Password=tizone_1234
 
 
#DriverClass=oracle.jdbc.driver.OracleDriver

#Url=jdbc:oracle:thin:@10.10.7.116:1530:TIPLUSDB

#UserName=TIZONE

#Password=tizone_1234
 
 
#SIT Server

#DriverClass=oracle.jdbc.driver.OracleDriver

#Url=jdbc:oracle:thin:@10.10.20.137:1528:orcl1

#UserName=TIZONE

#Password=tizone_1234
 
 
#Development Server

#DriverClass=oracle.jdbc.driver.OracleDriver

#Url=jdbc:oracle:thin:@10.24.201.195:1525:TIPLUS

#Url=jdbc:oracle:thin:@10.24.201.195:1525/TIPLUS

#UserName=TIZONE1

#Password=tizone123
 
#**********  CLOSE URL *********************

#CloseUrl=https://tiplusdevapp:9443/tradepro-global

#CloseUrl=https://tiplusdevapp:9443/tradepro-global

#EjbUrl=iiop://10.10.19.179:2811
 
#PreProduction EJBURL

#EjbUrl=iiop://10.10.7.137:9812
 
#UAT3 EJBURL

EjbUrl=iiop://localhost:9812
 
#UAT Server

#DriverClass=oracle.jdbc.driver.OracleDriver

#Url=jdbc:oracle:thin:@10.24.201.127:1525:TIPLUS

#UserName=TIZONE1

#Password=tizone123
 
 
#CloseUrl=https://tiplusapp1uat:9443/tiplus2-global/

#EjbUrl=iiop://10.24.201.128:2810
 
#ett cloud

#DriverClass=oracle.jdbc.driver.OracleDriver

#Url=jdbc:oracle:thin:@172.16.25.5:1521:orcl

#UserName=KMBZONE

#Password=Wise@123