#SERVICE=AvailBal
#SERVICE=LimitFetch
SERVICE=Posting
API_END_URL=https://apimuat.unionbankofindia.co.in/BankServices/handlersb/1/UFUATCHANNEL/UFUATSERVICEGROUP/balanceEnquiryService
ENCRYPTION_KEY=4336118faef74c988a489c802ca1fdd1