#COMMON FILES
label.firc.ok = OK
label.firc.validate = Validate
label.firc.close = Close
label.firc.cancel = Reset
label.firc.error = Error Description
label.firc.error.severity = Severity
label.firc.error.description = Description
label.firc.error.steps = Steps
label.firc.error.details = Details
label.firc.error.overridden = Overridden
label.firc.error = Error Description