#SIT 
#DriverClass=oracle.jdbc.driver.OracleDriver
#Url=jdbc:oracle:thin:@10.10.20.137:1528:orcl1
#UserName=TIZONE
#Password=tizone_1234
 
#UAT 2
#DriverClass=oracle.jdbc.driver.OracleDriver
#Url=jdbc:oracle:thin:@10.10.7.211:1532:tireport
#UserName=TIZONE
#Password=tizone_1234
 
 
#UAT 3
#DriverClass=oracle.jdbc.driver.OracleDriver
#Url=jdbc:oracle:thin:@10.10.20.137:1530:orcl
#UserName=TIZONE
#Password=tizone_1234
 
#PRE-PROD
#DriverClass = oracle.jdbc.driver.OracleDriver
#Url = jdbc:oracle:thin:@10.10.7.211:1530:tiplusdb
#UserName = TIZONE
#Password = tizone_1234
 
#PRE-PROD REPORT
#DriverClass = oracle.jdbc.driver.OracleDriver
#Url = jdbc:oracle:thin:@10.10.7.211:1532:tireport
#UserName = TIZONE
#Password = tizone_1234
 
 
#WF ZONE
#DriverClass = oracle.jdbc.driver.OracleDriver
Url = jdbc:oracle:thin:@10.128.230.200:1529:FTRADE
UserName = UBZONE
Password = Cisco123