#************************************************
#**********  DB Information *********************
 
#Localization
 
JNDIConnection = true
JNDICONTEXT = com.ibm.websphere.naming.WsnInitialContextFactory
 
 
#106
#JNDI_PROVIDER_URL = t3://172.19.36.106
#JNDIPORT = 7004
#JNDIZONE = jdbc/zone
 
#DR-Server
#JNDI_PROVIDER_URL = t3://10.17.16.51
#JNDIPORT = 7114
#JNDIZONE = jdbc/zone
 
#107
JNDI_PROVIDER_URL = t3://10.128.230.200
JNDIPORT = 1529
JNDIZONE = jdbc/zone
 
#PRE_PROD
#JNDI_PROVIDER_URL = t3://10.5.8.114
#JNDIPORT = 7114
#JNDIZONE = jdbc/zone
 
 
#PROD
#JNDI_PROVIDER_URL = t3://10.1.16.51
#JNDIPORT = 7114
#JNDIZONE = jdbc/zone
 
 
#Zone3
DriverClass = oracle.jdbc.driver.OracleDriver
 
 
#************************************************
#**********  END DB Information *****************