#************************************************
#********  CSV Download Information *************
 
 
obbcsvfilepath=/ftrade/FTI_Repositories/Localisation_logs/BOE_CSV_DOWLOAD/IDPMS/OBB
 
#obbcsvfilepath=D:/Arun_ETT
 
 
#************************************************
#********  END CSV Download Information *********