#************************************************

#**********  DB Information *********************
 
DriverClass=oracle.jdbc.driver.OracleDriver
Url=jdbc:oracle:thin:@10.128.230.200:1529/FTRADE
UserName=UBZONE
Password=Cisco123
EJBUrl=iiop://localhost:50034
 
 
 
 
 
 