
#Multiple Bills  Details
label.boe.close = Close
label.boe.PaymentReferenceNo = Payment Reference No
label.boe.PartPaymentSlNo = Part Payment SNo
label.boe.event.refNo = Event Reference No
label.boe.Search = Search
label.boe.PaymentDate = Payment Date
label.boe.CIFNO = CIF NO
label.boe.CustomerName = Customer Name
label.boe.IECode = IE Code
label.boe.PaymentCurrency = Payment Currency
label.boe.PaymentAmount = Payment Amount
label.boe.New = New
label.boe.Modify = Modify
label.boe.Severity = Severity
label.boe.Description = Description
label.boe.Steps = Steps
label.boe.Details = Details
label.boe.Overridden = Overridden
label.boe.BillOfEntryNo = Bill Of Entry No
label.boe.Endorse = Endorse
label.boe.Product = Product
label.boe.filterCurrency = Currency
label.boe.ProductType = Product Type
label.boe.FromDate = From Date
label.boe.ToDate = To Date
label.boe.exRate= Exchange Rate
label.boe.boeAllocAmt=Allocated Amount in BOE Currency
label.boe.BillofEntryCurrency = Bill of Entry Currency
label.boe.EndorsedByOtherAD = Endorsed By Other AD
label.boe.PaymentCurrency = Payment Currency
label.boe.EndorseAmount = BOE Endorsed Amount
label.boe.FullyAllocated = Fully Allocated
label.boe.Remarks = Remarks
label.boe.AllocatedAmount = BOE Allocated Amount 
label.boe.ActualAmountAvailable = BOE Amount Available For Endorsement
label.boe.BillofEntryAmount = Bill of Entry Amount
label.boe.BillofEntryDate = Bill of Entry Date
label.boe.OutstandingPayment = Outstanding Payment Amount
label.boe.EndorsedAmount = BOE Endorsed Amount
label.boe.PayEndorsedAmount = Payment Endorsed Amount
label.boe.BillofEntry = Bill of Entry
label.boe.BillofEntryType = Bill of Entry Type
label.boe.BillofEntryCurrency = Bill of Entry Currency
label.boe.BalanceAmountAvailable = Balance Amount Available
label.boe.AmountEndorsedByOtherAD = Endorsed By Other AD
label.boe.PaymentDetails = Payment Details
label.boe.Billofentryendorsement = Bill of Entry Endorsement
label.boe.OutstandingAmt =Bill Outstanding Amount
label.boe.AllocatedAmt = BOE Allocated Amount in Payment currency 
label.boe.PaymentReferencesDetails = Payment References Details
label.boe.portcode = Port Code
label.boe.harcode= Harmonised Code
label.boe.benefName = Counter Party Name 
label.boe.benefCountry = Counter Party Country 
label.boe.InvoiceDetails = Invoice Details
label.boe.InvoiceSerialNumber = Invoice Serial Number
label.boe.InvoiceNumber = Invoice Number
label.boe.InvoiceAmount = Invoice Amount
label.boe.RealizedAmount = Realized Amount
label.boe.igmNo=IGM No provided in Customs Document
label.boe.igmDate= IGM Date provided in Customs Document
label.boe.hblNo=House Airway Bill No/ House Bill of Lading No
label.boe.hblDate= House Airway Bill Date/ House Bill of Lading Date
label.boe.mblNo= Master Airway Bill No/ Master bill of Lading No 
label.boe.mblDate=Master Airway Bill Date/ Master bill of Lading Date
 
label.boe.IEAddress = IE Address
label.boe.IEPanNo = IE PAN Number
label.boe.AllocAmtPayCcy = Allocated Amount in Payment currency