CREATE OR REPLACE VIEW ETTV_BOE_PAYMENT_DETAILS (PD_CIF_ID, PD_CIF_NAME, BENEF_NAME, BENEF_COUNTRY, PD_TXN_DT, PD_TXN_REF, PD_PART_PAY_REF, PD_TXN_CCY, PD_FC_AMT, PD_ENDORSED_AMT, PD_OUTSTANDING_AMT, PD_EXG_RATE, PD_BASE_AMT, PD_IE_CODE, PD_PRD_CODE, PD_PRD_NAME, PD_PRD_TYPE, PD_EVE_CODE, PD_EVE_NEME, MAS_KEY, EVE_KEY) AS 
  SELECT 
  ECUS.CUST            AS PD_CIF_ID,
  PAD1.ADDRESS1                  AS PD_CIF_NAME,
  PAD2.ADDRESS1                  AS BENEF_NAME,
  PAD2.COUNTRY                   AS BENEF_COUNTRY,
  BEV.START_DATE                   AS PD_TXN_DT,
  MAS.MASTER_REF                 AS PD_TXN_REF,
  BEV.REFNO_PFIX||lPAD(BEV.REFNO_SERL,3,0) AS PD_PART_PAY_REF,
  PAP.PAY_AMTCCY                        AS PD_TXN_CCY,
  PAP.PAY_AMT/power(10,C82.C8CED)                     AS PD_FC_AMT,
  --(SELECT BOE_PAYMENT_BP_BOE_TYPE FROM ETT_BOE_PAYMENT WHERE TRIM(BOE_PAYMENT_BP_PAY_REF) = TRIM(MAS.MASTER_REF)) AS PD_BOE_TYPE,
  (SELECT SUM(NVL(BOE_PAYMENT_BP_PAY_ENDORSE_AMT, 0)) FROM ETT_BOE_PAYMENT WHERE TRIM(BOE_PAYMENT_BP_PAY_REF) = TRIM(MAS.MASTER_REF) AND  TRIM(BOE_PAYMENT_BP_PAY_PART_REF)=BEV.REFNO_PFIX||lPAD(BEV.REFNO_SERL,3,0)) AS PD_ENDORSED_AMT,
  (SELECT (PAP.PAY_AMT/power(10,C82.C8CED)) - SUM(NVL(BOE_PAYMENT_BP_PAY_ENDORSE_AMT,0)) FROM ETT_BOE_PAYMENT WHERE TRIM(BOE_PAYMENT_BP_PAY_REF)=TRIM(MAS.MASTER_REF)  AND  TRIM(BOE_PAYMENT_BP_PAY_PART_REF)=BEV.REFNO_PFIX||lPAD(BEV.REFNO_SERL,3,0)) AS PD_OUTSTANDING_AMT,
  EXRATE.SPOTRATE                AS PD_EXG_RATE,
  (PAP.PAY_AMT * EXRATE.SPOTRATE)/power(10,C82.C8CED) AS PD_BASE_AMT,
  ecus.iecode                    AS PD_IE_CODE,
  PRD.CODE79                     AS PD_PRD_CODE,
  PRD.LONGNA85                   AS PD_PRD_NAME,
   PRT.DESCRIP                    AS PD_PRD_TYPE,
  EVE.CODE79                     AS PD_EVE_CODE,
  EVE.LONGNA85                   AS PD_EVE_NEME,
  MAS.KEY97                      AS MAS_KEY,
  BEV.KEY97                      AS EVE_KEY
FROM MASTER MAS,
  PARTYDTLS PAD1,
  PARTYDTLS PAD2,
  BASEEVENT BEV,
  EXEMPL30 EVE,
  SPOTRATE EXRATE,
  exempl30 PRD,
  extcust ecus,
  GFPF G1,
  C8PF C82,
  PRODTYPE PRT,
  LCPAYMENT LCP,
  LCMASTER LC,
  PARTPAYMNT PAP
  WHERE 
  MAS.KEY97 = LC.KEY97
  AND LC.APP_PTY = PAD1.KEY97
  AND LC.BEN_PTY = PAD2.KEY97
--IMPORT LC - OUTSTANDING CLAIM -- APPLICANT IS CUSTOMER
--OUTWARD CUSTOMER REMITTANCE - REMITTER IS CUSTOMER
  AND MAS.KEY97        = BEV.MASTER_KEY
  AND BEV.EXEMPLAR     = EVE.KEY97
  AND MAS.EXEMPLAR     = PRD.KEY97
  AND BEV.KEY97 = LCP.KEY97
  AND LCP.KEY97     = PAP.PAYEV_KEY
  AND PAP.PAY_AMTCCY    = EXRATE.CURRENCY
  AND PRD.CODE79 = 'ILC'
  AND EVE.CODE79 ='POC'
  AND BEV.STATUS IN ('i','c')
  AND TRIM(pad1.cus_mnm)= TRIM(G1.GFCUS1)
  AND TRIM(PAD1.CUS_SBB)=TRIM(G1.GFCUS1_SBB)
  AND MAS.PRODTYPE = PRT.KEY97
  AND TRIM(G1.GFCUS1)=TRIM(ECUS.CUST)
  AND TRIM(G1.GFCUS1_SBB)=TRIM(ECUS.CUST_SBB)
  AND trim(BEV.CCY) = trim(C82.C8CCY )
  UNION ALL
  SELECT 
  ECUS.CUST            AS PD_CIF_ID,
  PAD1.ADDRESS1                  AS PD_CIF_NAME,
  PAD2.ADDRESS1                  AS BENEF_NAME,
  PAD2.COUNTRY                   AS BENEF_COUNTRY,
  BEV.START_DATE                   AS PD_TXN_DT,
  MAS.MASTER_REF                 AS PD_TXN_REF,
  BEV.REFNO_PFIX||lPAD(BEV.REFNO_SERL,3,0) AS PD_PART_PAY_REF,
  CPM.PAY_CCY                       AS PD_TXN_CCY,
  CPM.PAY_AMT/power(10,C82.C8CED)                     AS PD_FC_AMT,
  --(SELECT BOE_PAYMENT_BP_BOE_TYPE FROM ETT_BOE_PAYMENT WHERE TRIM(BOE_PAYMENT_BP_PAY_REF) = TRIM(MAS.MASTER_REF)) AS PD_BOE_TYPE,
  (SELECT SUM(NVL(BOE_PAYMENT_BP_PAY_ENDORSE_AMT, 0)) FROM ETT_BOE_PAYMENT WHERE TRIM(BOE_PAYMENT_BP_PAY_REF) = TRIM(MAS.MASTER_REF) AND  TRIM(BOE_PAYMENT_BP_PAY_PART_REF)=BEV.REFNO_PFIX||lPAD(BEV.REFNO_SERL,3,0)) AS PD_ENDORSED_AMT,
  (SELECT (CPM.PAY_AMT/power(10,C82.C8CED)) - SUM(NVL(BOE_PAYMENT_BP_PAY_ENDORSE_AMT,0)) FROM ETT_BOE_PAYMENT WHERE TRIM(BOE_PAYMENT_BP_PAY_REF)=TRIM(MAS.MASTER_REF)  AND  TRIM(BOE_PAYMENT_BP_PAY_PART_REF)=BEV.REFNO_PFIX||lPAD(BEV.REFNO_SERL,3,0)) AS PD_OUTSTANDING_AMT,
  EXRATE.SPOTRATE                AS PD_EXG_RATE,
  (CPM.PAY_AMT * EXRATE.SPOTRATE)/power(10,C82.C8CED) AS PD_BASE_AMT,
  ecus.iecode                    AS PD_IE_CODE,
  PRD.CODE79                     AS PD_PRD_CODE,
  PRD.LONGNA85                   AS PD_PRD_NAME,
  PRT.DESCRIP                    AS PD_PRD_TYPE,
  EVE.CODE79                     AS PD_EVE_CODE,
  EVE.LONGNA85                   AS PD_EVE_NEME,
  MAS.KEY97                      AS MAS_KEY,
  BEV.KEY97                      AS EVE_KEY
  FROM MASTER MAS,
  PARTYDTLS PAD1,
  PARTYDTLS PAD2,
  BASEEVENT BEV,
  EXEMPL30 EVE,
  SPOTRATE EXRATE,
  exempl30 PRD,
  extcust ecus,
  GFPF G1,
  C8PF C82,
  PRODTYPE PRT,
  CPAYMASTER CPM,
  tidataitem T
  WHERE 
--IMPORT LC - OUTSTANDING CLAIM -- APPLICANT IS CUSTOMER
--OUTWARD CUSTOMER REMITTANCE - REMITTER IS CUSTOMER
MAS.KEY97 = CPM.KEY97
AND MAS.key97 = t.master_key
AND T.KEY97 = PAD2.KEY97
AND PAD2.ROLE = 'BEN'
AND MAS.KEY97 = BEV.MASTER_KEY
AND CPM.REMIT_PTY = PAD1.KEY97
AND BEV.EXEMPLAR     = EVE.KEY97
AND MAS.EXEMPLAR     = PRD.KEY97
AND CPM.PAY_CCY          = EXRATE.CURRENCY
AND PRD.CODE79 ='CPCO'
AND EVE.CODE79 ='PCOC'
AND BEV.STATUS IN ('i','c')
AND TRIM(pad1.cus_mnm)= TRIM(G1.GFCUS1)
AND TRIM(PAD1.CUS_SBB)=TRIM(G1.GFCUS1_SBB)
AND MAS.PRODTYPE = PRT.KEY97
AND TRIM(G1.GFCUS1)=TRIM(ECUS.CUST)
AND TRIM(G1.GFCUS1_SBB)=TRIM(ECUS.CUST_SBB)
AND trim(BEV.CCY) = trim(C82.C8CCY )
UNION ALL
SELECT 
  ECUS.CUST            AS PD_CIF_ID,
  PAD1.ADDRESS1                  AS PD_CIF_NAME,
  PAD2.ADDRESS1                  AS BENEF_NAME,
  PAD2.COUNTRY                   AS BENEF_COUNTRY,
  BEV.START_DATE                   AS PD_TXN_DT,
  MAS.MASTER_REF                 AS PD_TXN_REF,
  BEV.REFNO_PFIX||lPAD(BEV.REFNO_SERL,3,0) AS PD_PART_PAY_REF,
  BEV.CCY                        AS PD_TXN_CCY,
  BEV.AMOUNT/power(10,C82.C8CED)                     AS PD_FC_AMT,
  --(SELECT BOE_PAYMENT_BP_BOE_TYPE FROM ETT_BOE_PAYMENT WHERE TRIM(BOE_PAYMENT_BP_PAY_REF) = TRIM(MAS.MASTER_REF)) AS PD_BOE_TYPE,
(SELECT SUM(NVL(BOE_PAYMENT_BP_PAY_EDS_FC_AMT, 0)) FROM ETT_BOE_PAYMENT WHERE TRIM(BOE_PAYMENT_BP_PAY_REF) = TRIM(MAS.MASTER_REF) AND  TRIM(BOE_PAYMENT_BP_PAY_PART_REF)=BEV.REFNO_PFIX||lPAD(BEV.REFNO_SERL,3,0)) AS PD_ENDORSED_AMT,
  (SELECT (BEV.AMOUNT/power(10,C82.C8CED)) - SUM(NVL(BOE_PAYMENT_BP_PAY_EDS_FC_AMT,0)) FROM ETT_BOE_PAYMENT WHERE TRIM(BOE_PAYMENT_BP_PAY_REF)=TRIM(MAS.MASTER_REF)
  AND  TRIM(BOE_PAYMENT_BP_PAY_PART_REF)=BEV.REFNO_PFIX||lPAD(BEV.REFNO_SERL,3,0)) AS PD_OUTSTANDING_AMT,
EXRATE.SPOTRATE                AS PD_EXG_RATE,
(BEV.AMOUNT * EXRATE.SPOTRATE)/power(10,C82.C8CED) AS PD_BASE_AMT,
  ecus.iecode                    AS PD_IE_CODE,
  PRD.CODE79                     AS PD_PRD_CODE,
  PRD.LONGNA85                   AS PD_PRD_NAME,
  PRT.DESCRIP                    AS PD_PRD_TYPE,
  EVE.CODE79                     AS PD_EVE_CODE,
  EVE.LONGNA85                   AS PD_EVE_NEME,
  MAS.KEY97                      AS MAS_KEY,
  BEV.KEY97                      AS EVE_KEY
FROM MASTER MAS,
  PARTYDTLS PAD1,
  PARTYDTLS PAD2,
  BASEEVENT BEV,
  EXEMPL30 EVE,
  SPOTRATE EXRATE,
  exempl30 PRD,
  extcust ecus,
  GFPF G1,
  C8PF C82,
  PRODTYPE PRT,
  COLLMASTER COL
  WHERE
 MAS.KEY97 = COL.KEY97
AND COL.DRAWEE_PTY  = PAD1.KEY97
AND COL.DRAWER_PTY = PAD2.KEY97
---INWARD DOCUMENTARY COLLECTION - PAYMENT - DRAWEE IS CUSTOMER
AND MAS.KEY97        = BEV.MASTER_KEY
AND BEV.EXEMPLAR     = EVE.KEY97
AND MAS.EXEMPLAR     = PRD.KEY97
AND BEV.CCY          = EXRATE.CURRENCY
AND PRD.CODE79 ='IDC'
AND EVE.CODE79 ='CRE'
--AND EVE.CODE79 ='CLP'
AND BEV.STATUS IN ('i','c')
AND TRIM(pad1.cus_mnm)= TRIM(G1.GFCUS1)
AND TRIM(PAD1.CUS_SBB)=TRIM(G1.GFCUS1_SBB)
AND MAS.PRODTYPE = PRT.KEY97
AND TRIM(G1.GFCUS1)=TRIM(ECUS.CUST)
AND TRIM(G1.GFCUS1_SBB)=TRIM(ECUS.CUST_SBB)
AND trim(BEV.CCY) = trim(C82.C8CCY );
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE ETT_BOE_PAYMENT 
   (	BOE_PAYMENT_CIF_ID CHAR(20 BYTE), 
	BOE_PAYMENT_CIF_NAME CHAR(35 BYTE), 
	BOE_PAYMENT_BP_BOE_NO VARCHAR2(30 BYTE), 
	BOE_PAYMENT_BP_BOE_TYPE CHAR(20 BYTE), 
	BOE_PAYMENT_BP_BOE_DT DATE, 
	BOE_PAYMENT_BP_PAY_DT DATE, 
	BOE_PAYMENT_BP_PAY_REF CHAR(30 BYTE), 
	BOE_PAYMENT_BP_PAY_PART_REF CHAR(20 BYTE), 
	BOE_PAYMENT_BP_PAY_CCY CHAR(3 BYTE), 
	BOE_PAYMENT_BP_PAY_FC_AMT NUMBER(18,2), 
	BOE_PAYMENT_BP_PAY_EDS_FC_AMT NUMBER(18,2), 
	BOE_PAYMENT_BP_PAY_OS_FC_AMT NUMBER(18,2), 
	BOE_PAYMENT_BP_PAY_FC_FULL_AMT NUMBER(18,2), 
	BOE_PAYMENT_BP_PAY_FULL_YN CHAR(1 BYTE), 
	CREATEDDATE TIMESTAMP (6), 
	LASTUPDATE TIMESTAMP (6), 
	BOE_ENTRY_AMT NUMBER(18,2), 
	BOE_PAYMENT_BP_BOE_CCY CHAR(3 BYTE), 
	USERID VARCHAR2(20 BYTE), 
	AMOUNTOTHERAD NUMBER(18,2), 
	ACTUALAMT NUMBER(18,2), 
	BOE_PAYMENT_BP_PAY_ENDORSE_AMT NUMBER(18,2), 
	REMARKS VARCHAR2(100 BYTE), 
	STATUS VARCHAR2(20 BYTE), 
	UPDATED_BY VARCHAR2(50 BYTE), 
	PORT_CODE VARCHAR2(20 BYTE), 
	HCODEE VARCHAR2(20 BYTE), 
	BOE_PAYMENT_BENEF_NAME VARCHAR2(35 BYTE), 
	BOE_PAYMENT_BENEF_COUNTRY VARCHAR2(20 BYTE), 
	AMOUNT_USD NUMBER(18,2), 
	AMOUNT_INR NUMBER(18,2), 
	GOODSCODE VARCHAR2(10 BYTE), 
	PSU VARCHAR2(1 BYTE), 
	CAPITAL_GOODS VARCHAR2(1 BYTE), 
	BOE_MAWB_MBLNUMBER VARCHAR2(30 BYTE), 
	BOE_MAWB_MBLDATE DATE, 
	BOE_HAWB_HBLNUMBER VARCHAR2(30 BYTE), 
	BOE_HAWB_HBLDATE DATE, 
	BOE_IGMNUMBER VARCHAR2(30 BYTE), 
	BOE_IGMDATE DATE, 
	IECODE VARCHAR2(20 BYTE), 
	ADCODE VARCHAR2(20 BYTE), 
	RECORD_INDICATOR VARCHAR2(20 BYTE), 
	IMPORT_AGENCY CHAR(1 BYTE), 
	PORT_OF_SHIPMENT CHAR(50 BYTE)
   );
   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    CREATE TABLE ETT_BOE_INV_PAYMENT 
   (	INV_SNO VARCHAR2(20 BYTE), 
	INV_NO VARCHAR2(20 BYTE), 
	INV_AMT VARCHAR2(20 BYTE), 
	REAL_AMT VARCHAR2(20 BYTE), 
	REAL_ORM_AMT VARCHAR2(20 BYTE), 
	BOE_NO VARCHAR2(20 BYTE), 
	BOE_DATE DATE, 
	TERMS_OF_INVOICE VARCHAR2(30 BYTE), 
	INVOICECURR VARCHAR2(3 BYTE), 
	EOD_STATUS VARCHAR2(1 BYTE)
   );
   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------
   CREATE TABLE ETT_BOE_DETAILS 
   (	BOE_NUMBER VARCHAR2(20 BYTE), 
	BOE_DATE DATE, 
	BOE_PORT_OF_DISCHARGE VARCHAR2(6 BYTE), 
	BOE_IMPORT_AGENCY VARCHAR2(1 BYTE), 
	BOE_AD_CODE VARCHAR2(7 BYTE), 
	BOE_GP VARCHAR2(10 BYTE), 
	BOE_IE_CODE VARCHAR2(10 BYTE), 
	BOE_IE_NAME VARCHAR2(100 BYTE), 
	BOE_IE_ADDRESS VARCHAR2(200 BYTE), 
	BOE_IE_PANNUMBER VARCHAR2(30 BYTE), 
	BOE_PORT_OF_SHIPMENT VARCHAR2(50 BYTE), 
	BOE_RECORD_INDICATOR VARCHAR2(50 BYTE), 
	BOE_PORT_CODE VARCHAR2(10 BYTE), 
	CIF VARCHAR2(12 BYTE), 
	BOE_MAWB_MBLNUMBER VARCHAR2(30 BYTE), 
	BOE_MAWB_MBLDATE DATE, 
	BOE_HAWB_HBLNUMBER VARCHAR2(30 BYTE), 
	BOE_HAWB_HBLDATE DATE, 
	BOE_IGMNUMBER VARCHAR2(30 BYTE), 
	BOE_IGMDATE DATE
   );
   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------
   CREATE TABLE ETT_INVOICE_DETAILS 
   (	BOE_NUMBER VARCHAR2(20 BYTE), 
	BOE_DATE DATE, 
	BOE_PORT_OF_DISCHARGE VARCHAR2(6 BYTE), 
	INVOICE_SERIAL_NUMBER VARCHAR2(10 BYTE), 
	INVOICE_NUMBER VARCHAR2(50 BYTE), 
	INVOICE_TERMS_OF_INVOICE VARCHAR2(50 BYTE), 
	INVOICE_SUPPLIER_NAME VARCHAR2(100 BYTE), 
	INVOICE_SUPPLIER_ADDRESS VARCHAR2(200 BYTE), 
	INVOICE_SUPPLIER_COUNTRY VARCHAR2(30 BYTE), 
	INVOICE_SELLER_NAME VARCHAR2(100 BYTE), 
	INVOICE_SELLER_ADDRESS VARCHAR2(200 BYTE), 
	INVOICE_SELLER_COUNTRY VARCHAR2(30 BYTE), 
	INVOICE_FOBAMOUNT NUMBER(16,4), 
	INVOICE_FOBCURRENCY VARCHAR2(3 BYTE), 
	INVOICE_FRIEGHTAMOUNT NUMBER(16,4), 
	INVOICE_FRIEGHTCURRENCYCODE VARCHAR2(3 BYTE), 
	INVOICE_INSURANCEAMOUNT NUMBER(16,4), 
	INVOICE_INSURANCECURRENCY_CODE VARCHAR2(3 BYTE), 
	INVOICE_AGENCY_COMMISSION NUMBER(16,4), 
	INVOICE_AGENCY_CURRENCY VARCHAR2(3 BYTE), 
	INVOICE_DISCOUNT_CURRENCY VARCHAR2(3 BYTE), 
	INVOICE_DISCOUNT_CHARGES NUMBER(16,4), 
	INVOICE_MISCELLANEOUS_CHARGES NUMBER(16,4), 
	INVOICE_MISCELLANEOUS_CURRENCY VARCHAR2(3 BYTE), 
	INVOICE_THIRDPARTY_NAME VARCHAR2(100 BYTE), 
	INVOICE_THIRDPARTY_ADDRESS VARCHAR2(200 BYTE), 
	INVOICE_THIRDPARTY_COUNTRY VARCHAR2(3 BYTE), 
	REMIFOB_AMOIN_ORMCURR VARCHAR2(3 BYTE), 
	REMIFOBAMO_EQUIFOBCURR VARCHAR2(3 BYTE), 
	REMIFREITAMOIN_ORMCURR VARCHAR2(3 BYTE), 
	REMI_FREITAMO_IN_EQU_FOB_CURR VARCHAR2(3 BYTE), 
	REMI_INSU_AMO_IN_ORM_CURR VARCHAR2(3 BYTE), 
	REMI_INSU_AMO_EQUI_ORM_CURR VARCHAR2(3 BYTE)
   );
   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------
   create or replace 
procedure ett_invoice_calc_insert (alloc_amt IN varchar2,boe_alloc_amt in VARCHAR2, total_amt in VARCHAR2, boe in varchar2, boe_date in varchar2) AS 
cursor c1 IS 
select 
invoice_serial_number as invoice_serial, 
invoice_number as invoice_no, 
invoice_fobamount as invoice_amt,
boe_number as boe_no,
boe_date as boe_date
from ett_invoice_details where boe_number=boe and boe_date = TO_DATE(TO_CHAR(boe_date,'DD-MM-YY'),'DD-MM-YY');
 
INV DECIMAL(15,2);
BILL DECIMAL(15,2);
TOTAL_BILL DECIMAL(15,2);
REALAMT DECIMAL(15,2);
REALAMT2 DECIMAL(15,2);
 
begin
  --DBMS_OUTPUT_LINE('--- '||REC1.INVOICE_AMT);
for rec1 in c1 loop 
  INV := TO_NUMBER (rec1.invoice_amt);
  dbms_output.put_line('product_code - '||INV);
  --BILL:=
  REALAMT:=(INV*TO_NUMBER(alloc_amt))/TO_NUMBER(total_amt);
  REALAMT2:=(INV*TO_NUMBER(boe_alloc_amt))/TO_NUMBER(total_amt);
  dbms_output.put_line('product_code2 - '||REALAMT);
  --update ett_boe_inv_payment set real_amt=REALAMT,real_orm_amt=REALAMT where boe_no=rec1.boe_no and inv_sno=rec1.invoice_serial and inv_no=rec1.invoice_no;
  INSERT INTO ett_boe_inv_payment(INV_SNO,INV_NO,INV_AMT,REAL_AMT,real_orm_amt,BOE_NO,boe_date) VALUES(rec1.invoice_serial,rec1.invoice_no,rec1.invoice_amt,REALAMT,REALAMT2,rec1.boe_no,TO_DATE(TO_CHAR(rec1.boe_date,'DD-MM-YY'),'DD-MM-YY'));
end loop;
end;
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE ETT_MANUAL_PORTCODES 
   (	PORT_CODE VARCHAR2(30 BYTE)
   );
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------