package in.co.boe.utility;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.Font.FontFamily;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import in.co.boe.vo.BoeVO;
import java.io.FileOutputStream;
import java.io.InputStream;
import org.apache.commons.io.IOUtils;
 
public class BarcodeGenerator
{
  public void writeBOEAckData(BoeVO boeVO)
    throws Exception
  {
    Document document = new Document(new Rectangle(PageSize.A4));
    String fileName = String.valueOf(boeVO.getPaymentRefNo()) + boeVO.getPartPaymentSlNo();
    PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(String.valueOf(ActionConstants.FILE_LOCATION) + fileName + ".pdf"));
    Font fontTitle = new Font(Font.FontFamily.COURIER, 12.0F, 1, BaseColor.BLACK);
    Font fontList = new Font(Font.FontFamily.COURIER, 10.0F, 0, BaseColor.BLACK);
    Paragraph para1 = new Paragraph();
    Paragraph para2 = new Paragraph();
    Paragraph para3 = new Paragraph();
    Paragraph para4 = new Paragraph();
    Paragraph para5 = new Paragraph();
    Paragraph para6 = new Paragraph();
    Paragraph para7 = new Paragraph();
    Paragraph para8 = new Paragraph();
    Paragraph para9 = new Paragraph();
    Paragraph para10 = new Paragraph();
    Paragraph para11 = new Paragraph();
    Paragraph para12 = new Paragraph();
    Paragraph para13 = new Paragraph();
    Paragraph para14 = new Paragraph();
    para1.setFont(fontList);
    para2.setFont(fontList);
    para3.setFont(fontList);
    para4.setFont(fontList);
    para5.setFont(fontList);
    para6.setFont(fontList);
    para7.setFont(fontList);
    para8.setFont(fontList);
    para9.setFont(fontList);
    para10.setFont(fontList);
    para11.setFont(fontList);
    para12.setFont(fontList);
    para13.setFont(fontList);
    para14.setFont(fontList);
    InputStream anInputStream = BarcodeGenerator.class.getClassLoader().getResourceAsStream("in/co/boe/resources/kotak_logo.jpg");
    Image img = Image.getInstance(IOUtils.toByteArray(anInputStream));
    img.scaleAbsolute(505.0F, 40.0F);
    Chunk boeTitle = new Chunk("BILL OF ENTRY ACKNOWLEDGEMENT", fontTitle);
    para1.setAlignment(0);
    para1.add(boeTitle);
    Chunk d1 = new Chunk("Date :");
    para2.setAlignment(0);
    para2.add(d1);
    para2.add(new Chunk(" " + boeVO.getPos()));
    Chunk d2 = new Chunk("We hereby acknowledge receipt of the Bill of Entry/Postal/Courier Wrapper as per the datails provided below: ");
    para3.setAlignment(0);
    para3.add(d2);
    Chunk d3 = new Chunk("Name & Address of the Importer  ");
    para4.setAlignment(0);
    para4.add(d3);
    para4.add(new Chunk(" :  " + boeVO.getIename()));
    Chunk ieAddr1 = new Chunk("                                ");
    para8.setAlignment(0);
    para8.add(ieAddr1);
    para8.add(new Chunk("    " + boeVO.getIeAddr1()));
    Chunk ieAddr2 = new Chunk("                                ");
    para9.setAlignment(0);
    para9.add(ieAddr2);
    para9.add(new Chunk("    " + boeVO.getIeAddr2()));
    Chunk ieAddr3 = new Chunk("                                ");
    para10.setAlignment(0);
    para10.add(ieAddr3);
    para10.add(new Chunk("    " + boeVO.getIeAddr3()));
    Chunk ieAddr4 = new Chunk("                                ");
    para14.setAlignment(0);
    para14.add(ieAddr4);
    para14.add(new Chunk(" :  " + boeVO.getIeAddr4()));
    Chunk d4 = new Chunk("IE Code No  ");
    para5.setAlignment(0);
    para5.add(d4);
    para5.add(new Chunk(" :  " + boeVO.getIeCode()));
    Chunk d6 = new Chunk("Our Bill Reference  ");
    para7.setAlignment(0);
    para7.add(d6);
    para7.add(new Chunk(" :  " + boeVO.getPaymentRefNo() + "-" + boeVO.getPartPaymentSlNo()));
    PdfPTable table = new PdfPTable(4);
    table.setWidthPercentage(90.0F);
    PdfPCell cell1 = new PdfPCell(new Phrase("BOE No", fontList));
    cell1.setPadding(5.0F);
    cell1.setHorizontalAlignment(0);
    table.addCell(cell1);
    PdfPCell cell2 = new PdfPCell(new Phrase("BOE Date", fontList));
    cell2.setPadding(5.0F);
    cell2.setHorizontalAlignment(0);
    table.addCell(cell2);
    PdfPCell cell3 = new PdfPCell(new Phrase("BOE Amount", fontList));
    cell3.setPadding(5.0F);
    cell3.setHorizontalAlignment(0);
    table.addCell(cell3);
    PdfPCell cell4 = new PdfPCell(new Phrase("Endorsed Amount", fontList));
    cell4.setPadding(5.0F);
    cell4.setHorizontalAlignment(0);
    table.addCell(cell4);
    PdfPCell columnCell1 = new PdfPCell(new Phrase(boeVO.getBoeNo(), fontList));
    columnCell1.setPadding(5.0F);
    columnCell1.setHorizontalAlignment(0);
    table.addCell(columnCell1);
    PdfPCell columnCell2 = new PdfPCell(new Phrase(boeVO.getBoeDate(), fontList));
    columnCell2.setPadding(5.0F);
    columnCell2.setHorizontalAlignment(0);
    table.addCell(columnCell2);
    PdfPCell columnCell3 = new PdfPCell(new Phrase(String.valueOf(boeVO.getBoeAmt()) + " " + boeVO.getBoeCurr(), fontList));
    columnCell3.setPadding(5.0F);
    columnCell3.setHorizontalAlignment(0);
    table.addCell(columnCell3);
    PdfPCell columnCell4 = new PdfPCell(new Phrase(String.valueOf(boeVO.getEndorseAmt()) + " " + boeVO.getBoeCurr(), fontList));
    columnCell4.setPadding(5.0F);
    columnCell4.setHorizontalAlignment(0);
    table.addCell(columnCell4);
    float[] colWidths = { 20.0F, 20.0F, 30.0F, 30.0F };
    table.setWidths(colWidths);
    Chunk d7 = new Chunk("Date Of Remittance  ");
    para11.setAlignment(0);
    para11.add(d7);
    para11.add(new Chunk(" :  " + boeVO.getPaymentDate()));
    Chunk d8 = new Chunk("Particulars of Goods  ");
    para12.setAlignment(0);
    para12.add(d8);
    para12.add(new Chunk(" :  " + boeVO.getGovprv()));
    Chunk d9 = new Chunk("This is computer generated advise.Does not require signature.");
    para13.setAlignment(0);
    para13.add(d9);
    document.open();
    document.add(img);
    float[] columnWidths1 = { 10.0F };
    PdfPTable table1 = new PdfPTable(columnWidths1);
    table1.setWidthPercentage(100.0F);
    table1.getDefaultCell().setBorder(0);
    table1.getDefaultCell().setHorizontalAlignment(1);
    table1.addCell(para1);
    document.add(table1);
    document.add(Chunk.NEWLINE);
    document.add(para2);
    document.add(Chunk.NEWLINE);
    document.add(para3);
    document.add(Chunk.NEWLINE);
    document.add(para4);
    document.add(para8);
    document.add(para9);
    document.add(para10);
    document.add(Chunk.NEWLINE);
    document.add(para5);
    document.add(Chunk.NEWLINE);
    document.add(para7);
    document.add(Chunk.NEWLINE);
    document.add(table);
    document.add(Chunk.NEWLINE);
    document.add(para11);
    document.add(Chunk.NEWLINE);
    document.add(para12);
    document.add(Chunk.NEWLINE);
    document.add(Chunk.NEWLINE);
    document.add(Chunk.NEWLINE);
    float[] columnWidths2 = { 10.0F };
    PdfPTable table3 = new PdfPTable(columnWidths2);
    table3.setWidthPercentage(100.0F);
    table3.getDefaultCell().setBorder(0);
    table3.getDefaultCell().setHorizontalAlignment(1);
    table3.addCell(para13);
    document.add(table3);
    document.close();
    writer.close();
  }
}
