#************************************************
#**********  DB Information *********************
 
 
 
#**********  CLOSE URL *********************
#CloseUrl=https://tiapp-uat.anb.com.sa/tiplus2-global
 
 
##KOTAK-SIT
 
#DriverClass=oracle.jdbc.driver.OracleDriver
#Url=jdbc:oracle:thin:@10.10.20.137:1528/orcl1
#UserName=TIZONE
#Password=tizone_1234
#CloseUrl=https://10.10.20.136:443/tiplus2-global/login
 
 
DriverClass=oracle.jdbc.driver.OracleDriver
Url=jdbc:oracle:thin:@10.128.230.200:1529:FTRADE
UserName=UBZONE
Password=Ubzo#2023
CloseUrl=https://10.128.231.197:8002/tiplus2-deploy1
 
#PREPRODREPORTZONE-UAT2
#DriverClass=oracle.jdbc.driver.OracleDriver
#Url=jdbc:oracle:thin:@10.10.7.211:1532/tireport
#UserName=TIZONE
#Password=tizone_1234
#CloseUrl=https://10.10.20.183:443/tiplus2-global
 
 
 
#KOTAK-UAT2
#DriverClass=oracle.jdbc.driver.OracleDriver
#Url=jdbc:oracle:thin:@10.10.19.179:1528/orcl2
#UserName=TIZONE
#Password=tizone_1234
#CloseUrl=https://10.10.20.183:443/tiplus2-global
 
#KOTAK-UAT3
#DriverClass=oracle.jdbc.driver.OracleDriver
#Url=jdbc:oracle:thin:@10.10.20.137:1530/orcl
#UserName=tizone
#Password=tizone_1234
#CloseUrl=https://10.10.20.165/tiplus2-global
 
## PREPRODUCTION
 
#DriverClass=oracle.jdbc.driver.OracleDriver
#Url=jdbc:oracle:thin:@10.10.7.211:1530/tiplusdb
#UserName=TIZONE
#Password=tizone_1234
 
 
 
 
#**********  CLOSE URL *********************
 
 
#https://10.10.20.183:443/tiplus2-deploy1
#CloseUrl=https://10.10.20.165:443/tiplus2-global/login