#COMMON FILES

label.gr.ok = OK
label.gr.validate = Validate
label.gr.close = Close
label.gr.cancel = Reset
label.gr.error = Error Description
label.gr.error.severity = Severity
label.gr.error.description = Description
label.gr.error.steps = Steps
label.gr.error.details = Details
label.gr.error.overridden = Overridden
label.gr.error = Error Description
label.gr.transfer = Transfer Details
 
label.gr.inputdetails = Input Details
label.gr.transaction = Transaction Details Section
label.gr.trans.refno = Transaction Reference No
label.gr.trans.eventno = Transaction Event Reference No
label.gr.trans.date = Transaction Date
label.gr.trans.curr = Transaction Currency
label.gr.trans.amt = Transaction Amount
 
#XML FILE UPLOAD PROCESS

label.gr.xmlFileUpload.title = XML File Upload Process
 
#AD TRANSFER

label.gr.adtransfer.title = AD-Transfer
label.gr.adtransfer.shipno = Shipping Bill No
label.gr.adtransfer.portcode = Port Code
label.gr.adtransfer.exp.agency = Export Agency
label.gr.adtransfer.ex.adcode = Existing AdCode
label.gr.adtransfer.ie.code = IE Code
label.gr.adtransfer.shipdate = Shipping Bill Date
label.gr.adtransfer.formNo = Form No
label.gr.adtransfer.exp.type = Type of Export
label.gr.adtransfer.new.adcode = New ADCode
 
#REALIZATION

label.gr.realization.title = Realization Process
label.gr.realization.bill.refNo = Bill Reference No
label.gr.realization.billcurr = Bill Currency
label.gr.realization.cus.cifno = Customer CIF No
label.gr.realization.event.no = Event Reference No
label.gr.realization.billAmt = Bill Amount
label.gr.realization.cus.name = Customer Name
label.gr.realization.cus.ser = Customer Serial NO
label.gr.realization.ad.code = AD Code
label.gr.realization.ad.coun.des = Country of Destination
 
label.gr.shipping.details = Shipping Details
label.gr.invoice.details = Invoice Details 
label.gr.edpms.search = EDPMS Utilize Search
label.gr.realization.cus.det = Customer Details
label.gr.realization.cus.list = Customer List
 
label.gr.realization.ship.bill.curr = Shipping Bill Currency 
label.gr.realization.ship.billAmt = Shipping Bill Amount 
label.gr.realization.ex.rate = Exchange Rate
label.gr.realization.inv.title = Invoice Details Sections
label.gr.realization.ship.title  = Shipping Details Section
label.gr.ship.real.amt = Realization Amount
label.gr.ship.cut.real.amt = Current Realization Amount
label.gr.ship.write.amt = Write-off Amount
label.gr.ship.bankchrgs = Bank Charges
label.gr.ship.boeNo = BOE Number
label.gr.ship.boeDate = BOE Date
label.gr.ship.portDischarge = Port Of Discharge
 
label.gr.ship.real.curr = Realization Currency
label.gr.ship.cut.real.curr = Current Realization Currency
label.gr.ship.write.ind = Write-off Indicator Date 
label.gr.ship.avl.real.amt = Already Realized Amount
label.gr.ship.total.real.amt = Total Realized Amount
label.gr.ship.pay.serialNo = Payment Serial No
 
 
label.gr.realization.inv.ser.no = Invoice Serial No
label.gr.realization.inv.no = Invoice No
label.gr.realization.inv.date = Invoice Date
label.gr.realization.inv.realcurr = Realized Currency Code
label.gr.realization.inv.ex.curr = Exchange Currency
label.gr.realization.inv.fob = FOB Amount
label.gr.realization.inv.freight = Freight Amount
label.gr.realization.inv.ins = Insurance Amount
label.gr.realization.inv.comm = Commission  Amount
label.gr.realization.inv.ded = Deduction Amount
label.gr.realization.inv.dis = Discount Amount
label.gr.realization.inv.pkg = Packing Amount
label.gr.ship.write.date = Write-off Date 
label.gr.ship.write.off.ind = Write-off Indicator
 
 
label.gr.ack.prn.sent = PRN Status
label.gr.ack.pen.sent = PEN Status
label.gr.ack.rod.sent = ROD Status
label.gr.ack.gr.type = GR Type
label.gr.realization.inv.remit.coun = Remitter Country 
label.gr.realization.inv.remit.name = Remitter Name
label.gr.realization.inv.remit.close = Close of Bill Indicator
label.gr.realization.inv.fobamt = Invoice FOB Amount
label.gr.realization.inv.freightamt = Invoice Freight Amount
label.gr.realization.inv.insamt =  Invoice Insurance Amount
label.gr.realization.inv.commamt = Invoice Commission  Amount
label.gr.realization.inv.dedamt = Invoice Deduction Amount
label.gr.realization.inv.disamt = Invoice Discount Amount
label.gr.realization.inv.pkgamt = Invoice Packing Amount
label.gr.realization.date = Realization Date
label.gr.realization.ship.indicator = Shipment Indicator
label.gr.realization.real.status = Realization Status
 
label.gr.realized.inv.fobamt = Current FOB Amount
label.gr.realized.inv.freightamt = Current Freight Amount
label.gr.realized.inv.insamt =  Current Insurance Amount
label.gr.realized.inv.commamt = Current Commission  Amount
label.gr.realized.inv.dedamt = Current Deduction Amount
label.gr.realized.inv.disamt = Current Discount Amount
label.gr.realized.inv.pkgamt = Current Packing Amount
 
label.gr.realized.inv.fobamtIC = Current FOB Amount IC
label.gr.realized.inv.freightamtIC = Current Freight Amount IC
label.gr.realized.inv.insamtIC =  Current Insurance Amount IC
label.gr.realized.inv.commamtIC = Current Commission  Amount IC
label.gr.realized.inv.dedamtIC = Current Deduction Amount IC
label.gr.realized.inv.disamtIC = Current Discount Amount IC
label.gr.realized.inv.pkgamtIC = Current Packing Amount IC
 
 
label.gr.all.realized.inv.fobamt = Realized FOB Amount
label.gr.all.realized.inv.freightamt =  Realized Freight Amount
label.gr.all.realized.inv.insamt =  Realized Insurance Amount
label.gr.all.realized.inv.commamt =  Realized Commission  Amount
label.gr.all.realized.inv.dedamt =  Realized Deduction Amount
 label.gr.all.realized.inv.disamt =  Realized Discount Amount
label.gr.all.realized.inv.pkgamt =  Realized Packing Amount
label.gr.all.realized.inv.amt =  Realized Invoice Amount
 
 
label.gr.all.realized.inv.fobamtIC = Realized FOB Amount IC
label.gr.all.realized.inv.freightamtIC =  Realized Freight AmountIC
label.gr.all.realized.inv.insamtIC =  Realized Insurance Amount IC
label.gr.all.realized.inv.commamtIC =  Realized Commission  Amount IC
label.gr.all.realized.inv.dedamtIC =  Realized Deduction Amount IC
label.gr.all.realized.inv.disamtIC =  Realized Discount Amount IC
label.gr.all.realized.inv.pkgamtIC =  Realized Packing Amount IC
 
 
label.gr.total.realized.inv.fobamt = Total Realized FOB Amount
label.gr.total.realized.inv.freightamt = Total Realized Freight Amount
label.gr.total.realized.inv.insamt = Total Realized Insurance Amount
label.gr.total.realized.inv.commamt = Total Realized Commission  Amount
label.gr.total.realized.inv.dedamt = Total Realized Deduction Amount
label.gr.total.realized.inv.disamt = Total Realized Discount Amount
label.gr.total.realized.inv.pkgamt = Total Realized Packing Amount
 
 
label.gr.total.realized.inv.fobamtIC = Total Realized FOB Amount IC
label.gr.total.realized.inv.freightamtIC = Total Realized Freight Amount IC
label.gr.total.realized.inv.insamtIC = Total Realized Insurance Amount IC
label.gr.total.realized.inv.commamtIC = Total Realized Commission  Amount IC
label.gr.total.realized.inv.dedamtIC = Total Realized Deduction Amount IC
label.gr.total.realized.inv.disamtIC = Total Realized Discount Amount IC
label.gr.total.realized.inv.pkgamtIC = Total Realized Packing Amount IC
 
 
#EDMPS Process

label.gr.edmps.ti.details = TIPLUS Details
label.gr.edmps.ship.details = GR Process Shipping Bill Details
 
 
label.gr.ack.rod.title = Receipt of Document Acknowledgement
label.gr.ack.irm.title = IRM Acknowledgement
label.gr.ack.irfirc.title = IRFIRC Acknowledgement
label.gr.ack.pen.title = Payment Extension Acknowledgement
label.gr.ack.prn.title = Payment Realization Acknowledgement
label.gr.ack.trr.title = AD Transfer Acknowledgement
label.gr.ack.wsn.title = Write Off/Set Off Acknowledgement
label.gr.ack.rod.details = ROD Acknowledgement Details
label.gr.ack.irm.details = IRM Acknowledgement Details
label.gr.ack.irfirc.details = IRFIRC Acknowledgement Details
label.gr.ack.pen.details = PEN Acknowledgement Details
label.gr.ack.trr.details = TRR Acknowledgement Details
label.gr.ack.wsn.shp.details = WSN Shipping Acknowledgement Details
label.gr.ack.wsn.inv.details = WSN Invoice Acknowledgement Details
label.gr.ack.prn.shp.details = PRN Shipping Acknowledgement Details
label.gr.ack.prn.inv.details = PRN Invoice Acknowledgement Details
 
label.gr.ack.rod.adcode = AD Code
label.gr.ack.rod.exp.type = Export Type
label.gr.ack.rod.red = Record Indicator 
label.gr.ack.rod.leo = LEO Date
label.gr.ack.rod.ch.iecode = Changed IE Code
label.gr.ack.rod.iecode =  IE Code
label.gr.ack.rod.ddi = Direct Dispatch Indicator
label.gr.ack.rod.adbillno = AD BillNo
label.gr.ack.rod.date = Date of NGO
label.gr.ack.rod.buyername = Buyer Name
label.gr.ack.rod.buyercountry = Buyer Country
label.gr.ack.rod.error = Error Codes
 
label.gr.ack.pen.letterno = Letter No
label.gr.ack.pen.letterdate = Letter Date
label.gr.ack.pen.real.date = Extend Realization Date
label.gr.ack.pen.real.ext.ind = Realization Extension IND
label.gr.ack.pen.trans.date = Transmission Date
 
label.gr.ack.wsn.inv.ser.no = Invoice Serial No
label.gr.ack.wsn.inv.no = Invoice No
label.gr.ack.wsn.inv.date = Invoice Date
label.gr.ack.wsn.inv.shp.ind = Shipment IND
label.gr.ack.wsn.inv.wr.amt = Write Off Amount
label.gr.ack.wsn.inv.wr.date = Write Off Date
label.gr.ack.wsn.inv.wr.ind = Write Off IND
label.gr.ack.wsn.inv.close.ind = Close Bill IND
label.gr.ack.wsn.inv.error = Invoice Error Codes
 
 
label.gr.ack.wsn.inv.status = Realization Status
label.gr.ack.wsn.firc.no = FIRC No
label.gr.ack.wsn.firc.adcode = FIRC AD Code
label.gr.ack.wsn.inv.real.curr = Realization Currency Code
label.gr.ack.wsn.inv.real.date = Realization Date
label.gr.ack.wsn.inv.acc.no = Account No
label.gr.ack.wsn.inv.bank = Banking Charges
label.gr.ack.wsn.inv.fob= FOB Amt
label.gr.ack.wsn.inv.fobic = FOB AmtIc 
label.gr.ack.wsn.inv.freight = Freight Amt
label.gr.ack.wsn.inv.freightic = Freight AmtIc
label.gr.ack.wsn.inv.ins = Insurance Amt
label.gr.ack.wsn.inv.insic = Insurance AmtIc
label.gr.ack.wsn.inv.comm = Commission Amt
label.gr.ack.wsn.inv.commic = Commission AmtIc
label.gr.ack.wsn.inv.ded = Deduction Amt
label.gr.ack.wsn.inv.dedic = Deduction AmtIc
label.gr.ack.wsn.inv.dis = Discount Amt
label.gr.ack.wsn.inv.disic = Discount AmtIc
label.gr.ack.wsn.inv.pak = Packing Amt
label.gr.ack.wsn.inv.pakic = Packing AmtIc
 
 