#SERVER

ROD_ONLINE=/opt/Localization/EDPMS/ROD_ONLINE/
TRR_ONLINE=/opt/Localization/EDPMS/TRR_ONLINE/
PRN_ONLINE=/opt/Localization/EDPMS/PRN_ONLINE/
IRM_ONLINE=/opt/Localization/EDPMS/IRM_ONLINE/
PEN_ONLINE=/opt/Localization/EDPMS/PEN_ONLINE/
WSN_ONLINE=/opt/Localization/EDPMS/WSN_ONLINE/
EBRC_ONLINE=/opt/Localization/EDPMS/EBRC_ONLINE/
IREXT_ONLINE=/opt/Localization/EDPMS/IREXT_ONLINE/
IRCLS_ONLINE=/opt/Localization/EDPMS/IRCLS_ONLINE/
IRFIRC_ONLINE=/opt/Localization/EDPMS/IRFIRC_ONLINE/
CANCEL_EBRC_ONLINE=/opt/Localization/EDPMS/CANCEL_EBRC_ONLINE/
CANCEL_IRCLS_ONLINE=/opt/Localization/EDPMS/CANCEL_IRCLS_ONLINE/
 
#LOCAL

#ROD_ONLINE=D:/EOD/
#TRR_ONLINE=D:/EOD/
#PRN_ONLINE=D:/EOD/
#IRM_ONLINE=D:/EOD/
#PEN_ONLINE=D:/EOD/
#WSN_ONLINE=D:/EOD/
#EBRC_ONLINE=D:/EOD/
#IREXT_ONLINE=D:/EOD/
#IRCLS_ONLINE=D:/EOD/
#IRFIRC_ONLINE=D:/EOD/
#CANCEL_EBRC_ONLINE=D:/EOD/
#CANCEL_IRCLS_ONLINE=D:/EOD/
 