package in.co.chargeSchedule.utility;

import java.util.Collections;
import java.util.Map;

public abstract interface ActionConstants
{
  public static final String SYSTEM = "SYSTEM";
  public static final String APPROVE = "approve";
  public static final String REJECT = "reject";
  public static final String REJECT1 = "REJECTED";
  public static final String ENTERING_METHOD = "Entering Method";
  public static final String EXITING_METHOD = "Exiting Method";
  public static final String Y = "Y";
  public static final String N = "N";
  public static final String FALSE = "false";
  public static final String TRUE = "true";
  public static final String USERID_QUERY = "select skey80 from secage88 where name85 =?";
  public static final String USER_ID = "skey80";
  public static final String USERID = "USERID";
  public static final String PO_MAKER = "POMAKER";
  public static final String PO_CHECKER = "POCHECKER";
  public static final String PO_VIEWER = "POVIEWER";
  public static final String MAKER = "maker";
  public static final String CHECKER = "checker";
  public static final String VIEWER = "viewer";
  public static final String MAKER_CHECKER = "both";
  public static final String ONE = "1";
  public static final String TWO = "2";
  public static final String THREE = "3";
  public static final String FOUR = "4";
  public static final String COL_COUNT = "Count";
  public static final String TEAMKEY = "teamkey";
  public static final String PENDING = "P";
  public static final String APPROVAL = "A";
  public static final String FAIL = "fail";
  public static final String SUCCESS1 = "success";
  public static final String userName = "UBZONE";
  public static final String password = "Cisco123";
  public static final String dbName = "UAT_UBZONE";
  public static final String url = "jdbc:oracle:thin:@10.128.230.200:1529:FTRADE";
  public static final String driver = "com.mysql.jdbc.Driver";
  public static final String CHARGE_QUERY = "select id, descr, KEY97 from RELTEMPLTE where obsolete ='N' AND TYPEFLAG=10136";
  public static final String CHARGE_FILTER_QUERY = "â€‹select id,descr,KEY97 from RELTEMPLTE where obsolete ='N'";
  public static final String CUSTOMER_LIST_QUERY = "select GFCPNC,GFCUN from GFPF order by GFCPNC";
  public static final String CUS_NUM_FILTER_QUERY = "select GFCPNC AS CIFID,GFCUN AS CUSTOMER from GFPF ";
  public static final String PRODUCT_RETRIVE_QUERY = "â€‹SELECT code79 as product,longna85 as description,key97 FROM exempl30 where typeflag=13270 ";
  public static final String RETRIVE_QUERY = "SELECT  R.ID, R.DESCR, R.KEY97, C.CODE79, C.CUS_MNM FROM ETT_CHARGE99_DET C,RELTEMPLTE R WHERE R.ID=C.CHG_TYPE AND C.OBSOLETE='N' AND C.STATUS ='MA'  AND R.TYPEFLAG=10136";
  public static final String insert_Export = "insert into ett_export_order(Export_Order_date,Beneficiary_Name,Inco_Terms,Goods_Code,PO_Value,Currency,Expiry_Date,Last_Shipment_Date,Percentage_Freight_Deduction,Percentage_Insurance_Deduction,Margin_percentage,Eligible_amount,Importer_Name,user_id,maker_timestamp,status,GOODS_DESC,INWARD_NO,Export_Order_Number,CIF_ID,NTP,DUE_DATE,SHPMODE) values(to_date(?,'dd/mm/yyyy'),?,?,?,?,?,to_date(?,'dd/mm/yyyy'),to_date(?,'dd/mm/yyyy'),?,?,?,?,?,?,SYSTIMESTAMP,?,?,?,?,?,?,to_date(?,'dd/mm/yyyy'))";
  public static final String UPDATE_EXPORT = "UPDATE ETT_EXPORT_ORDER SET EXPORT_ORDER_DATE=to_date(?,'dd/mm/yyyy'),BENEFICIARY_NAME=?,INCO_TERMS=?,GOODS_CODE=?,PO_VALUE=?,CURRENCY=?,EXPIRY_DATE=to_date(?,'dd/mm/yyyy'),LAST_SHIPMENT_DATE=to_date(?,'dd/mm/yyyy'),PERCENTAGE_FREIGHT_DEDUCTION=?,PERCENTAGE_INSURANCE_DEDUCTION=?,MARGIN_PERCENTAGE=?,ELIGIBLE_AMOUNT=?,IMPORTER_NAME=?,USER_ID=?,MAKER_TIMESTAMP=SYSTIMESTAMP,STATUS=?,GOODS_DESC=?,INWARD_NO=?,NTP=?,DUE_DATE=to_date(?,'dd/mm/yyyy'),SHPMODE=? WHERE EXPORT_ORDER_NUMBER=? AND CIF_ID=? ";
  public static final String GET_PURCHASE_ORDER_STATUS = "SELECT COUNT(1) FROM ETT_EXPORT_ORDER WHERE EXPORT_ORDER_NUMBER = ? AND CIF_ID = ? AND STATUS='R' ";
  public static final String fetchincoreterms = "select code79,incote33 from incote48";
  public static final String filterincoreterms = "select code79,incote33 from incote48 where code79='";
  public static final String fetchPurchase = "select Export_Order_Number,TO_CHAR(TO_DATE(Export_Order_date,'DD/MM/YY'),'dd/mm/YYYY') AS Export_Order_date,CIF_ID,Beneficiary_Name,Inco_Terms,Goods_Code,PO_Value,Currency,TO_CHAR(TO_DATE(Expiry_Date,'DD/MM/YY'),'dd/mm/YYYY') AS Expiry_Date,TO_CHAR(TO_DATE(Last_Shipment_Date,'DD/MM/YY'),'dd/mm/YYYY') AS Last_Shipment_Date,Percentage_Freight_Deduction,Percentage_Insurance_Deduction,Margin_percentage,Eligible_amount,importer_name,INWARD_NO,TO_CHAR(GOODS_DESC) GOODS_DESC from ett_export_order where Export_Order_Number= ? ";
  public static final String fetchPurchaseorder = "select Export_Order_Number,TO_CHAR(TO_DATE(Export_Order_date,'DD/MM/YY'),'dd/mm/YYYY') AS Export_Order_date,CIF_ID,Beneficiary_Name,Inco_Terms,Goods_Code,PO_Value,Currency,TO_CHAR(TO_DATE(Expiry_Date,'DD/MM/YY'),'dd/mm/YYYY') AS Expiry_Date,TO_CHAR(TO_DATE(Last_Shipment_Date,'DD/MM/YY'),'dd/mm/YYYY') AS Last_Shipment_Date,Percentage_Freight_Deduction,Percentage_Insurance_Deduction,Margin_percentage,Eligible_amount,importer_name from ett_export_order where CIF_ID= ? ";
  public static final String PO_NO = "PO_NO";
  public static final String PO_DATE = "PO_DATE";
  public static final String CIF = "CIF";
  public static final String BEN_NAME = "BEN_NAME";
  public static final String INCO = "INCO";
  public static final String GOODS = "GOODS";
  public static final String PO_VAL = "PO_VAL";
  public static final String CURR = "CURR";
  public static final String EXPIRY_DATE = "EXPIRY_DATE";
  public static final String LAST_SHIPMENT_DATE = "LAST_SHIPMENT_DATE";
  public static final String FREIGHT = "FREIGHT";
  public static final String INSURANCE = "INSURANCE";
  public static final String AMOUNT = "AMOUNT";
  public static final String IMPORTER = "IMPORTER";
  public static final String MARGIN = "MARGIN";
  public static final String findcurrency = "select count(*) from c8pf where c8ccy='";
  public static final String CHARGE_ID = "ID";
  public static final String CHARGE_DESC = "descr";
  public static final String CHARGE_KEY97 = "KEY97";
  public static final String GET_PURCHASE_DETAILS_CIF = "SELECT EXPORT_ORDER_NUMBER AS PO_NO,TO_CHAR(EXPORT_ORDER_DATE,'DD/MM/YY') AS PO_DATE,CIF_ID AS CIF,BENEFICIARY_NAME AS BEN_NAME,INCO_TERMS AS INCO,GOODS_CODE AS GOODS,PO_VALUE AS PO_VAL,CURRENCY AS CURR,TO_CHAR(EXPIRY_DATE,'DD/MM/YY') AS EXPIRY_DATE,TO_CHAR(LAST_SHIPMENT_DATE,'DD/MM/YY') AS LAST_SHIPMENT_DATE,PERCENTAGE_FREIGHT_DEDUCTION AS FREIGHT,PERCENTAGE_INSURANCE_DEDUCTION AS INSURANCE,ELIGIBLE_AMOUNT AS AMOUNT,IMPORTER_NAME AS IMPORTER,MARGIN_PERCENTAGE AS MARGIN FROM ETT_EXPORT_ORDER ";
  public static final String GET_PURCHASE_DETAIL = "SELECT EXPORT_ORDER_NUMBER AS PO_NO,TO_CHAR(EXPORT_ORDER_DATE,'DD/MM/YY') AS PO_DATE,CIF_ID AS CIF,BENEFICIARY_NAME AS BEN_NAME,INCO_TERMS AS INCO,GOODS_CODE AS GOODS,PO_VALUE AS PO_VAL,CURRENCY AS CURR,TO_CHAR(EXPIRY_DATE,'DD/MM/YY') AS EXPIRY_DATE,TO_CHAR(LAST_SHIPMENT_DATE,'DD/MM/YY') AS LAST_SHIPMENT_DATE,PERCENTAGE_FREIGHT_DEDUCTION AS FREIGHT,PERCENTAGE_INSURANCE_DEDUCTION AS INSURANCE,ELIGIBLE_AMOUNT AS AMOUNT,IMPORTER_NAME AS IMPORTER,MARGIN_PERCENTAGE AS MARGIN FROM ETT_EXPORT_ORDER ";
  public static final String PRODUCT_ID = "product";
  public static final String PRODUCT_DESC = "description";
  public static final String PRODUCT_KEY97 = "KEY97";
  public static final String CUS_MNM = "CUS_MNM";
  public static final String CODE79 = "CODE79";
  public static final String INCOTE33 = "INCOTE33";
  public static final String SCREEN_ID = "CS01";
  public static final String CIF_NO = "0";
  public static final String CIF_CHARGE_NULL = "1";
  public static final String CIF_NULL = "2";
  public static final String CHARGE_NULL = "3";
  public static final String CIF_CHARGE_ALREADY_USED = "4";
  public static final String FAILED = "5";
  public static final String DEFINE_CHARGE = "6";
  public static final String PRODUCT_NULL = "7";
  public static final String PENDING_FOR_APPROVAL = "8";
  public static final String INVALID_CURRENCY = "11";
  public static final String INVALID_SHIPMENT_DATE = "14";
  public static final String INVALID_EXPIRY_DATE = "13";
  public static final String INVALID_PO_DATE = "15";
  public static final String INVALID_PO_NUMBER = "16";
  public static final String INCO_TERMS = "17";
  public static final String DUPLICATE = "12";
  public static final String FRAME = "FRAME";
  public static final String Impo_Name = "18";
  public static final String PO_Date1 = "19";
  public static final String Expiry_Date = "20";
  public static final String Ship_Date = "21";
  public static final String PO_value1 = "22";
  public static final String Ex_GRE = "23";
  public static final String PO_Date_Shipment_Date = "25";
  public static final String PO_Date_Expirt_Date = "24";
  public static final String PO_Date_Ship_Expirt_Date = "26";
  public static final String SHIPMENT_EXPO_DATE = "27";
  public static final String PO_Date_Future = "28";
  public static final String PO_VALUE_NEGATIVE = "29";
  public static final String PO_VALUE_INVALID = "30";
  public static final String BEN_IMP_NAME_EQUAL = "31";
  public static final String INVALID_EXP_DATE = "32";
  public static final String Destination_country = "33";
  public static final String NCIF_check = "34";
  public static final String LASTSHIPMENT_EXPIRY_DATE = "35";
  public static final String BRANCH = "BRANCH";
  public static final String CHRG_GRP = "CHRG_GRP";
  public static final String SCHED_TYPE = "SCHED_TYPE";
  public static final String CCY = "CCY";
  public static final String PERD_AMT = "PERD_AMT";
  public static final String CHGS_WAIVE = "CHGS_WAIVE";
  public static final String PERIODIC = "PERIODIC";
  public static final String ADV_ARR = "ADV_ARR";
  public static final String OVERALLMIN = "OVERALLMIN";
  public static final String OVERALLMAX = "OVERALLMAX";
  public static final String SPLIT = "SPLIT";
  public static final String T1_AMT = "T1_AMT";
  public static final String T1_MINAMT = "T1_MINAMT";
  public static final String T1_MAXAMT = "T1_MAXAMT";
  public static final String T1_NO = "T1_NO";
  public static final String T1_UNIT = "T1_UNIT";
  public static final String T1_FRQ = "T1_FRQ";
  public static final String TIERAMT1 = "TIERAMT1";
  public static final String T1_BASE = "T1_BASE";
  public static final String T1_DIFF = "T1_DIFF";
  public static final String T1_INTRATE = "T1_INTRATE";
  public static final String T1_PERCENT = "T1_PERCENT";
  public static final String T2_AMT = "T2_AMT";
  public static final String T2_MINAMT = "T2_MINAMT";
  public static final String T2_MAXAMT = "T2_MAXAMT";
  public static final String T2_NO = "T2_NO";
  public static final String T2_UNIT = "T2_UNIT";
  public static final String T2_FRQ = "T2_FRQ";
  public static final String TIERAMT2 = "TIERAMT2";
  public static final String T2_BASE = "T2_BASE";
  public static final String T2_DIFF = "T2_DIFF";
  public static final String T2_INTRATE = "T2_INTRATE";
  public static final String T2_PERCENT = "T2_PERCENT";
  public static final String T3_AMT = "T3_AMT";
  public static final String T3_MINAMT = "T3_MINAMT";
  public static final String T3_MAXAMT = "T3_MAXAMT";
  public static final String T3_NO = "T3_NO";
  public static final String T3_UNIT = "T3_UNIT";
  public static final String T3_FRQ = "T3_FRQ";
  public static final String TIERAMT3 = "TIERAMT3";
  public static final String T3_BASE = "T3_BASE";
  public static final String T3_DIFF = "T3_DIFF";
  public static final String T3_INTRATE = "T3_INTRATE";
  public static final String T3_PERCENT = "T3_PERCENT";
  public static final String T4_AMT = "T4_AMT";
  public static final String T4_MINAMT = "T4_MINAMT";
  public static final String T4_MAXAMT = "T4_MAXAMT";
  public static final String T4_NO = "T4_NO";
  public static final String T4_UNIT = "T4_UNIT";
  public static final String T4_FRQ = "T4_FRQ";
  public static final String TIERAMT4 = "TIERAMT4";
  public static final String T4_BASE = "T4_BASE";
  public static final String T4_DIFF = "T4_DIFF";
  public static final String T4_INTRATE = "T4_INTRATE";
  public static final String T4_PERCENT = "T4_PERCENT";
  public static final String STRDTE = "STRDTE";
  public static final String EXPDTE = "EXPDTE";
  public static final String NULL = "null";
  public static final String ETT_EXPORT_ORDER_QUERY = "select Export_Order_Number,TO_CHAR(TO_DATE(Export_Order_date,'DD/MM/YY'),'dd/mm/YYYY') AS Export_Order_date, CIF_ID,Beneficiary_Name,Inco_Terms,Goods_Code,PO_Value,Currency,TO_CHAR(TO_DATE(Expiry_Date,'DD/MM/YY'),'dd/mm/YYYY') AS Expiry_Date, TO_CHAR(TO_DATE(Last_Shipment_Date,'DD/MM/YY'),'dd/mm/YYYY') AS Last_Shipment_Date,Percentage_Freight_Deduction, Percentage_Insurance_Deduction,Margin_percentage,Eligible_amount,importer_name from ett_export_order where STATUS='P' AND USER_ID <> ";
  public static final String ETT_EXPORT_ORDER_ENQUIRY = "select Export_Order_Number,TO_CHAR(TO_DATE(Export_Order_date,'DD/MM/YY'),'dd/mm/YYYY') AS Export_Order_date,STATUS, CIF_ID,Beneficiary_Name,Inco_Terms,Goods_Code,PO_Value,Currency,TO_CHAR(TO_DATE(Expiry_Date,'DD/MM/YY'),'dd/mm/YYYY') AS Expiry_Date, TO_CHAR(TO_DATE(Last_Shipment_Date,'DD/MM/YY'),'dd/mm/YYYY') AS Last_Shipment_Date,Percentage_Freight_Deduction, Percentage_Insurance_Deduction,Margin_percentage,Eligible_amount,importer_name from ett_export_order where  Export_Order_Number=Export_Order_Number ";
  public static final String SINGLE_PO_DETAILS = "select STATUS,EXPORT_ORDER_NUMBER,TO_CHAR(TO_DATE(EXPORT_ORDER_DATE,'DD/MM/YY'),'dd/mm/YYYY') AS EXPORT_ORDER_DATE,CIF_ID,BENEFICIARY_NAME,INCO_TERMS,GOODS_CODE, PO_VALUE,CURRENCY,IMPORTER_NAME,TO_CHAR(TO_DATE(Expiry_Date,'DD/MM/YY'),'dd/mm/YYYY') AS EXPIRY_DATE,TO_CHAR(TO_DATE(Last_Shipment_Date,'DD/MM/YY'),'dd/mm/YYYY') AS LAST_SHIPMENT_DATE,PERCENTAGE_FREIGHT_DEDUCTION, PERCENTAGE_INSURANCE_DEDUCTION,MARGIN_PERCENTAGE,ELIGIBLE_AMOUNT, TO_CHAR(GOODS_DESC) as GOODS_DESC, INWARD_NO,NTP,TO_CHAR(TO_DATE(DUE_DATE,'DD/MM/YY'),'dd/mm/YYYY') AS DUE_DATE,SHPMODE from ett_export_order where EXPORT_ORDER_NUMBER=? and CIF_ID=?";
  public static final String APPROVE_SINGLE_PO = "UPDATE ett_export_order SET STATUS ='A',UPDATED_BY=?,REMARKS=? WHERE EXPORT_ORDER_NUMBER =? AND CIF_ID=?";
  public static final String REJECT_SINGLE_PO = "UPDATE ett_export_order SET STATUS ='R',UPDATED_BY=?,REMARKS=?  WHERE EXPORT_ORDER_NUMBER =? AND CIF_ID=?";
  public static final String COL_CUSTOMER = "CUSTOMER";
  public static final String COL_BEN_NAME = "BEN_NAME";
  public static final String COL_SHIP_DATE = "SHIP_DATE";
  public static final String COL_GOODS_CODE = "GOODS_CODE";
  public static final String COL_GOODS_DESC = "GOODS_DESC";
  public static final String COL_INCO = "INCO";
  public static final String COL_EXPIRY_DATE = "EXPIRY_DATE";
  public static final String COL_IMPORTER = "APP_NAME";
  public static final String COL_AMT = "AMOUNT";
  public static final String COL_SMODE = "SMODE";
  public static final Map<String, String> REC3 = Collections.unmodifiableMap(new ActionConstants.1());
  public static final String PO_FIN_QUERY = "SELECT AMASTER.MASTER_REF,AEXTEVENTPPO.UFINAMT AS AMOUNT, AEXTEVENTPPO.CCY_2 AS CCY FROM MASTER AMASTER,BASEEVENT ABASEEVENT,EXTEVENTPPO AEXTEVENTPPO WHERE AMASTER.KEY97 = ABASEEVENT.MASTER_KEY AND ABASEEVENT.STATUS = 'c' AND ABASEEVENT.EXTFIELD = AEXTEVENTPPO.FK_EVENT AND TRIM(AEXTEVENTPPO.PON) = ?";
}
