package in.co.chargeSchedule.utility;

public abstract interface ActionConstantsQuery
extends ActionConstants
{
public static final String FETCHGOODSlIST = "SELECT CODE79,DESCRI73 FROM GOODSC87 WHERE CODE79=CODE79  ";
public static final String FETCHINWARDDETAILS = "SELECT TRIM(AMASTER.CCY), TRIM(AMASTER.MASTER_REF),TRIM(B.CUS_MNM),TRIM(AMASTER.AMOUNT)/POWER(10,TRIM(C82.C8CED)),TRIM(APPPARTYDTLS.ADDRESS1)   FROM MASTER AMASTER,LCMASTER ALCMASTER,PARTYDTLS B,C8PF C82,PARTYDTLS APPPARTYDTLS WHERE  AMASTER.KEY97 = ALCMASTER.KEY97 AND ALCMASTER.BEN_PTY = B.KEY97 AND  ALCMASTER.APP_PTY= \tAPPPARTYDTLS.KEY97 AND TRIM(C82.C8CCY)=trim(AMASTER.CCY) AND AMASTER.STATUS='LIV' ";
public static final String FETCH_MASTER_DETAILS = "SELECT  BENPARTYDTLS.CUS_MNM AS CUSTOMER , BENPARTYDTLS.ADDRESS1 AS BEN_NAME,  APPPARTYDTLS.ADDRESS1 AS APP_NAME, TO_CHAR(ALCMASTER.SHIP_DATE,'DD/MM/YYYY') AS SHIP_DATE,  ALCMASTER.GOODSCODE AS GOODS_CODE,  ALCMASTER.GOODS_DESC AS GOODS_DESC,  ALCMASTER.INCOTERMS AS INCO, TO_CHAR(AMASTER.EXPIRY_DAT,'DD/MM/YYYY') AS EXPIRY_DATE,(((AMASTER.AMT_O_S)/100)||' '||AMASTER.CCY) AS AMOUNT,EE.SMODE  FROM MASTER AMASTER,LCMASTER ALCMASTER,PARTYDTLS BENPARTYDTLS,PARTYDTLS APPPARTYDTLS,BASEEVENT BEV,EXTEVENT EE WHERE  AMASTER.KEY97 = \tALCMASTER.KEY97 AND ALCMASTER.BEN_PTY=  BENPARTYDTLS.KEY97 AND ALCMASTER.APP_PTY= \tAPPPARTYDTLS.KEY97 AND BEV.MASTER_KEY=AMASTER.KEY97 AND BEV.KEY97=EE.EVENT AND TRIM(AMASTER.MASTER_REF)=?";
public static final String isValidCurrency = "select COUNT(1) from c8pf where TRIM(C8CCY)=?";
public static final String isDataExists = "SELECT COUNT(1) FROM ETT_EXPORT_ORDER WHERE TRIM(EXPORT_ORDER_NUMBER)= ?  AND TRIM(CIF_ID)= ? AND UPPER(TRIM(STATUS)) !='R' ";
public static final String isRejectedData = "SELECT COUNT(1) FROM ETT_EXPORT_ORDER WHERE TRIM(EXPORT_ORDER_NUMBER)= ?  AND TRIM(CIF_ID)= ? AND UPPER(TRIM(STATUS)) !='A' ";
public static final String isValidCustomer = "select COUNT(1) from GFPF  WHERE TRIM(GFCPNC) = ?";
}
